// Mocks generated by Mockito 5.4.6 from annotations
// in coffee_timer/test/unit/widgets/recipe_screen_async_context_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i5;

import 'package:coffee_timer/database/database.dart' as _i2;
import 'package:coffee_timer/models/launch_popup_model.dart' as _i11;
import 'package:coffee_timer/models/recipe_model.dart' as _i8;
import 'package:coffee_timer/models/supported_locale_model.dart' as _i12;
import 'package:coffee_timer/providers/database_provider.dart' as _i3;
import 'package:coffee_timer/providers/recipe_provider.dart' as _i7;
import 'package:coffee_timer/providers/user_recipe_provider.dart' as _i13;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:uuid/uuid.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseProvider_1 extends _i1.SmartFake
    implements _i3.DatabaseProvider {
  _FakeDatabaseProvider_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_3 extends _i1.SmartFake implements _i5.Locale {
  _FakeLocale_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUuid_4 extends _i1.SmartFake implements _i6.Uuid {
  _FakeUuid_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecipeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeProvider extends _i1.Mock implements _i7.RecipeProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseProvider get databaseProvider =>
      (super.noSuchMethod(
            Invocation.getter(#databaseProvider),
            returnValue: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
            returnValueForMissingStub: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
          )
          as _i3.DatabaseProvider);

  @override
  List<_i8.RecipeModel> get recipes =>
      (super.noSuchMethod(
            Invocation.getter(#recipes),
            returnValue: <_i8.RecipeModel>[],
            returnValueForMissingStub: <_i8.RecipeModel>[],
          )
          as List<_i8.RecipeModel>);

  @override
  _i4.ValueNotifier<Set<String>> get shownBrewingMethodIds =>
      (super.noSuchMethod(
            Invocation.getter(#shownBrewingMethodIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#shownBrewingMethodIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#shownBrewingMethodIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  _i4.ValueNotifier<Set<String>> get hiddenBrewingMethodIds =>
      (super.noSuchMethod(
            Invocation.getter(#hiddenBrewingMethodIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#hiddenBrewingMethodIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#hiddenBrewingMethodIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  _i5.Locale get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _FakeLocale_3(this, Invocation.getter(#currentLocale)),
            returnValueForMissingStub: _FakeLocale_3(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as _i5.Locale);

  @override
  _i4.ValueNotifier<Set<String>> get favoriteRecipeIds =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteRecipeIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#favoriteRecipeIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#favoriteRecipeIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Future<void> ensureDataReady() =>
      (super.noSuchMethod(
            Invocation.method(#ensureDataReady, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setUserBrewingMethodPreference(
    String? methodId,
    bool? show,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setUserBrewingMethodPreference, [
              methodId,
              show,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> fetchAllRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllRecipes, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i8.RecipeModel>> fetchRecipesForBrewingMethod(
    String? brewingMethodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecipesForBrewingMethod, [brewingMethodId]),
            returnValue: _i9.Future<List<_i8.RecipeModel>>.value(
              <_i8.RecipeModel>[],
            ),
            returnValueForMissingStub: _i9.Future<List<_i8.RecipeModel>>.value(
              <_i8.RecipeModel>[],
            ),
          )
          as _i9.Future<List<_i8.RecipeModel>>);

  @override
  _i9.Future<String> getBrewingMethodName(String? brewingMethodId) =>
      (super.noSuchMethod(
            Invocation.method(#getBrewingMethodName, [brewingMethodId]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getBrewingMethodName, [brewingMethodId]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getBrewingMethodName, [brewingMethodId]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<_i8.RecipeModel?> getRecipeById(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [recipeId]),
            returnValue: _i9.Future<_i8.RecipeModel?>.value(),
            returnValueForMissingStub: _i9.Future<_i8.RecipeModel?>.value(),
          )
          as _i9.Future<_i8.RecipeModel?>);

  @override
  _i9.Future<void> toggleFavorite(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [recipeId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> saveCustomAmounts(
    String? recipeId,
    double? coffeeAmount,
    double? waterAmount, {
    String? customGrindSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveCustomAmounts,
              [recipeId, coffeeAmount, waterAmount],
              {#customGrindSize: customGrindSize},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> saveSliderPositions(
    String? recipeId, {
    int? sweetnessSliderPosition,
    int? strengthSliderPosition,
    int? coffeeChroniclerSliderPosition,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveSliderPositions,
              [recipeId],
              {
                #sweetnessSliderPosition: sweetnessSliderPosition,
                #strengthSliderPosition: strengthSliderPosition,
                #coffeeChroniclerSliderPosition: coffeeChroniclerSliderPosition,
              },
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i8.RecipeModel?> getLastUsedRecipe() =>
      (super.noSuchMethod(
            Invocation.method(#getLastUsedRecipe, []),
            returnValue: _i9.Future<_i8.RecipeModel?>.value(),
            returnValueForMissingStub: _i9.Future<_i8.RecipeModel?>.value(),
          )
          as _i9.Future<_i8.RecipeModel?>);

  @override
  _i9.Future<String> fetchBrewingMethodName(String? brewingMethodId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  List<_i8.RecipeModel> getFavoriteRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteRecipes, []),
            returnValue: <_i8.RecipeModel>[],
            returnValueForMissingStub: <_i8.RecipeModel>[],
          )
          as List<_i8.RecipeModel>);

  @override
  _i9.Future<List<_i8.RecipeModel>> fetchFavoriteRecipes(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFavoriteRecipes, [locale]),
            returnValue: _i9.Future<List<_i8.RecipeModel>>.value(
              <_i8.RecipeModel>[],
            ),
            returnValueForMissingStub: _i9.Future<List<_i8.RecipeModel>>.value(
              <_i8.RecipeModel>[],
            ),
          )
          as _i9.Future<List<_i8.RecipeModel>>);

  @override
  _i9.Future<List<_i8.RecipeModel>> fetchRecipesForVendor(String? vendorId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecipesForVendor, [vendorId]),
            returnValue: _i9.Future<List<_i8.RecipeModel>>.value(
              <_i8.RecipeModel>[],
            ),
            returnValueForMissingStub: _i9.Future<List<_i8.RecipeModel>>.value(
              <_i8.RecipeModel>[],
            ),
          )
          as _i9.Future<List<_i8.RecipeModel>>);

  @override
  _i9.Future<_i11.LaunchPopupModel?> fetchLatestLaunchPopup(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLatestLaunchPopup, [locale]),
            returnValue: _i9.Future<_i11.LaunchPopupModel?>.value(),
            returnValueForMissingStub:
                _i9.Future<_i11.LaunchPopupModel?>.value(),
          )
          as _i9.Future<_i11.LaunchPopupModel?>);

  @override
  _i9.Future<List<_i12.SupportedLocaleModel>> fetchAllSupportedLocales() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllSupportedLocales, []),
            returnValue: _i9.Future<List<_i12.SupportedLocaleModel>>.value(
              <_i12.SupportedLocaleModel>[],
            ),
            returnValueForMissingStub:
                _i9.Future<List<_i12.SupportedLocaleModel>>.value(
                  <_i12.SupportedLocaleModel>[],
                ),
          )
          as _i9.Future<List<_i12.SupportedLocaleModel>>);

  @override
  _i9.Future<String> getLocaleName(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#getLocaleName, [localeCode]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getLocaleName, [localeCode]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getLocaleName, [localeCode]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> setLocale(_i5.Locale? newLocale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [newLocale]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> getRandomCoffeeFactFromDB() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomCoffeeFactFromDB, []),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getRandomCoffeeFactFromDB, []),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getRandomCoffeeFactFromDB, []),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<String> getLocalizedRecipeName(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalizedRecipeName, [recipeId]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getLocalizedRecipeName, [recipeId]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getLocalizedRecipeName, [recipeId]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<List<String>> fetchAllDistinctRoasters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoasters, []),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i9.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<List<String>> fetchAllDistinctBeans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctBeans, []),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i9.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<List<String>> searchRoasters(String? filter) =>
      (super.noSuchMethod(
            Invocation.method(#searchRoasters, [filter]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i9.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<List<String>> searchBeans(String? filter) =>
      (super.noSuchMethod(
            Invocation.method(#searchBeans, [filter]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i9.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i9.Future<List<String>>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserRecipeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRecipeProvider extends _i1.Mock
    implements _i13.UserRecipeProvider {
  @override
  _i6.Uuid get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _FakeUuid_4(this, Invocation.getter(#uuid)),
            returnValueForMissingStub: _FakeUuid_4(
              this,
              Invocation.getter(#uuid),
            ),
          )
          as _i6.Uuid);

  @override
  List<_i8.RecipeModel> get userRecipes =>
      (super.noSuchMethod(
            Invocation.getter(#userRecipes),
            returnValue: <_i8.RecipeModel>[],
            returnValueForMissingStub: <_i8.RecipeModel>[],
          )
          as List<_i8.RecipeModel>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Future<void> createUserRecipe(_i8.RecipeModel? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#createUserRecipe, [recipe]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserRecipe(_i8.RecipeModel? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRecipe, [recipe]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteUserRecipe(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserRecipe, [recipeId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> unpublishRecipe(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#unpublishRecipe, [recipeId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> copyUserRecipe(_i8.RecipeModel? originalRecipe) =>
      (super.noSuchMethod(
            Invocation.method(#copyUserRecipe, [originalRecipe]),
            returnValue: _i9.Future<String?>.value(),
            returnValueForMissingStub: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> importSupabaseRecipe(
    Map<String, dynamic>? supabaseRecipeData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#importSupabaseRecipe, [supabaseRecipeData]),
            returnValue: _i9.Future<String?>.value(),
            returnValueForMissingStub: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> loadUserRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserRecipes, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserRecipeIdsAfterLogin(
    String? oldUserId,
    String? newUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRecipeIdsAfterLogin, [
              oldUserId,
              newUserId,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getUserRecipeName(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRecipeName, [recipeId]),
            returnValue: _i9.Future<String?>.value(),
            returnValueForMissingStub: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> checkModerationAfterLogin() =>
      (super.noSuchMethod(
            Invocation.method(#checkModerationAfterLogin, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<int> clearModerationFlagsForUnpublishedRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#clearModerationFlagsForUnpublishedRecipes, []),
            returnValue: _i9.Future<int>.value(0),
            returnValueForMissingStub: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
