// Mocks generated by Mockito 5.4.6 from annotations
// in coffee_timer/test/unit/widgets/recipe_detail_grind_autocomplete_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:coffee_timer/database/database.dart' as _i2;
import 'package:coffee_timer/models/coffee_beans_model.dart' as _i7;
import 'package:coffee_timer/models/diary_entry.dart' as _i11;
import 'package:coffee_timer/models/user_stat_model.dart' as _i10;
import 'package:coffee_timer/providers/coffee_beans_provider.dart' as _i4;
import 'package:coffee_timer/providers/database_provider.dart' as _i3;
import 'package:coffee_timer/providers/user_stat_provider.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseProvider_1 extends _i1.SmartFake
    implements _i3.DatabaseProvider {
  _FakeDatabaseProvider_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBeanWeightAdjustmentResult_2 extends _i1.SmartFake
    implements _i4.BeanWeightAdjustmentResult {
  _FakeBeanWeightAdjustmentResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCoffeeBeansProvider_3 extends _i1.SmartFake
    implements _i4.CoffeeBeansProvider {
  _FakeCoffeeBeansProvider_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CoffeeBeansProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoffeeBeansProvider extends _i1.Mock
    implements _i4.CoffeeBeansProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseProvider get databaseProvider =>
      (super.noSuchMethod(
            Invocation.getter(#databaseProvider),
            returnValue: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
            returnValueForMissingStub: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
          )
          as _i3.DatabaseProvider);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateCacheEntry(
    String? dataType,
    String? locale, {
    bool? isLocaleAgnostic = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #invalidateCacheEntry,
      [dataType, locale],
      {#isLocaleAgnostic: isLocaleAgnostic},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateDataType(String? dataType, {bool? isLocaleAgnostic = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #invalidateDataType,
          [dataType],
          {#isLocaleAgnostic: isLocaleAgnostic},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateExpiredEntries() => super.noSuchMethod(
    Invocation.method(#invalidateExpiredEntries, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> refreshDataType(
    String? dataType,
    String? locale, {
    bool? prefetch = false,
    bool? isLocaleAgnostic = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #refreshDataType,
              [dataType, locale],
              {#prefetch: prefetch, #isLocaleAgnostic: isLocaleAgnostic},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.CoffeeBeansModel>> fetchAllCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllCoffeeBeans, []),
            returnValue: _i6.Future<List<_i7.CoffeeBeansModel>>.value(
              <_i7.CoffeeBeansModel>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i7.CoffeeBeansModel>>.value(
                  <_i7.CoffeeBeansModel>[],
                ),
          )
          as _i6.Future<List<_i7.CoffeeBeansModel>>);

  @override
  _i6.Future<String> addCoffeeBeans(_i7.CoffeeBeansModel? beans) =>
      (super.noSuchMethod(
            Invocation.method(#addCoffeeBeans, [beans]),
            returnValue: _i6.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#addCoffeeBeans, [beans]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#addCoffeeBeans, [beans]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> updateCoffeeBeans(_i7.CoffeeBeansModel? beans) =>
      (super.noSuchMethod(
            Invocation.method(#updateCoffeeBeans, [beans]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCoffeeBeans(String? beansUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCoffeeBeans, [beansUuid]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.CoffeeBeansModel?> fetchCoffeeBeansById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCoffeeBeansById, [id]),
            returnValue: _i6.Future<_i7.CoffeeBeansModel?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i7.CoffeeBeansModel?>.value(),
          )
          as _i6.Future<_i7.CoffeeBeansModel?>);

  @override
  _i6.Future<_i7.CoffeeBeansModel?> fetchCoffeeBeansByUuid(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCoffeeBeansByUuid, [uuid]),
            returnValue: _i6.Future<_i7.CoffeeBeansModel?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i7.CoffeeBeansModel?>.value(),
          )
          as _i6.Future<_i7.CoffeeBeansModel?>);

  @override
  _i6.Future<List<String>> fetchAllDistinctRoasters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoasters, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctNames() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctNames, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctVarieties() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctVarieties, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctProcessingMethods() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctProcessingMethods, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctRoastLevels() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoastLevels, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctOrigins() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctOrigins, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctTastingNotes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctTastingNotes, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctRegions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRegions, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctFarmers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctFarmers, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctFarms() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctFarms, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctGrindSizes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctGrindSizes, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchCombinedTastingNotes(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedTastingNotes, [locale]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchCombinedOrigins(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedOrigins, [locale]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchCombinedProcessingMethods(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedProcessingMethods, [locale]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchCombinedRoasters(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedRoasters, [locale]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> toggleFavoriteStatus(String? uuid, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteStatus, [uuid, isFavorite]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> backfillMissingUuids() =>
      (super.noSuchMethod(
            Invocation.method(#backfillMissingUuids, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> batchUploadCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#batchUploadCoffeeBeans, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> batchDownloadCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#batchDownloadCoffeeBeans, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#syncCoffeeBeans, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncNewCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#syncNewCoffeeBeans, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.CoffeeBeansModel>> fetchFilteredCoffeeBeans({
    List<String>? roasters,
    List<String>? origins,
    bool? isFavorite,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFilteredCoffeeBeans, [], {
              #roasters: roasters,
              #origins: origins,
              #isFavorite: isFavorite,
            }),
            returnValue: _i6.Future<List<_i7.CoffeeBeansModel>>.value(
              <_i7.CoffeeBeansModel>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i7.CoffeeBeansModel>>.value(
                  <_i7.CoffeeBeansModel>[],
                ),
          )
          as _i6.Future<List<_i7.CoffeeBeansModel>>);

  @override
  _i6.Future<List<String>> fetchOriginsForRoasters(
    List<String>? selectedRoasters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOriginsForRoasters, [selectedRoasters]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<_i4.BeanWeightAdjustmentResult> adjustBeanWeightForDoseDelta(
    String? beansUuid,
    double? doseDelta,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#adjustBeanWeightForDoseDelta, [
              beansUuid,
              doseDelta,
            ]),
            returnValue: _i6.Future<_i4.BeanWeightAdjustmentResult>.value(
              _FakeBeanWeightAdjustmentResult_2(
                this,
                Invocation.method(#adjustBeanWeightForDoseDelta, [
                  beansUuid,
                  doseDelta,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.BeanWeightAdjustmentResult>.value(
                  _FakeBeanWeightAdjustmentResult_2(
                    this,
                    Invocation.method(#adjustBeanWeightForDoseDelta, [
                      beansUuid,
                      doseDelta,
                    ]),
                  ),
                ),
          )
          as _i6.Future<_i4.BeanWeightAdjustmentResult>);

  @override
  _i6.Future<double?> updateBeanWeightAfterBrew(
    String? beansUuid,
    double? usedAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightAfterBrew, [
              beansUuid,
              usedAmount,
            ]),
            returnValue: _i6.Future<double?>.value(),
            returnValueForMissingStub: _i6.Future<double?>.value(),
          )
          as _i6.Future<double?>);

  @override
  _i6.Future<double?> updateBeanWeightAfterBrewModification(
    String? beansUuid,
    double? coffeeAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightAfterBrewModification, [
              beansUuid,
              coffeeAmount,
            ]),
            returnValue: _i6.Future<double?>.value(),
            returnValueForMissingStub: _i6.Future<double?>.value(),
          )
          as _i6.Future<double?>);

  @override
  _i6.Future<double?> updateBeanWeightWhenBeansAdded(
    String? beansUuid,
    double? coffeeAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightWhenBeansAdded, [
              beansUuid,
              coffeeAmount,
            ]),
            returnValue: _i6.Future<double?>.value(),
            returnValueForMissingStub: _i6.Future<double?>.value(),
          )
          as _i6.Future<double?>);

  @override
  void printCacheStats() => super.noSuchMethod(
    Invocation.method(#printCacheStats, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserStatProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserStatProvider extends _i1.Mock implements _i9.UserStatProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i4.CoffeeBeansProvider get coffeeBeansProvider =>
      (super.noSuchMethod(
            Invocation.getter(#coffeeBeansProvider),
            returnValue: _FakeCoffeeBeansProvider_3(
              this,
              Invocation.getter(#coffeeBeansProvider),
            ),
            returnValueForMissingStub: _FakeCoffeeBeansProvider_3(
              this,
              Invocation.getter(#coffeeBeansProvider),
            ),
          )
          as _i4.CoffeeBeansProvider);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> insertUserStat({
    required String? recipeId,
    required double? coffeeAmount,
    required double? waterAmount,
    required int? sweetnessSliderPosition,
    required int? strengthSliderPosition,
    required String? brewingMethodId,
    String? notes,
    String? beans,
    String? roaster,
    double? rating,
    int? coffeeBeansId,
    bool? isMarked = false,
    String? coffeeBeansUuid,
    String? grindSize,
    double? waterTemp,
    int? tasteBalance,
    int? entrySource,
    String? tags,
    String? statUuid,
    DateTime? createdAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserStat, [], {
              #recipeId: recipeId,
              #coffeeAmount: coffeeAmount,
              #waterAmount: waterAmount,
              #sweetnessSliderPosition: sweetnessSliderPosition,
              #strengthSliderPosition: strengthSliderPosition,
              #brewingMethodId: brewingMethodId,
              #notes: notes,
              #beans: beans,
              #roaster: roaster,
              #rating: rating,
              #coffeeBeansId: coffeeBeansId,
              #isMarked: isMarked,
              #coffeeBeansUuid: coffeeBeansUuid,
              #grindSize: grindSize,
              #waterTemp: waterTemp,
              #tasteBalance: tasteBalance,
              #entrySource: entrySource,
              #tags: tags,
              #statUuid: statUuid,
              #createdAt: createdAt,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserStat({
    required String? statUuid,
    String? recipeId,
    double? coffeeAmount,
    double? waterAmount,
    int? sweetnessSliderPosition,
    int? strengthSliderPosition,
    String? brewingMethodId,
    String? notes,
    String? beans,
    String? roaster,
    double? rating,
    int? coffeeBeansId,
    bool? isMarked,
    String? coffeeBeansUuid,
    String? grindSize,
    double? tdsPercent,
    double? extractionYieldPercent,
    double? waterTemp,
    int? tasteBalance,
    int? entrySource,
    String? tags,
    bool? clearBeans = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStat, [], {
              #statUuid: statUuid,
              #recipeId: recipeId,
              #coffeeAmount: coffeeAmount,
              #waterAmount: waterAmount,
              #sweetnessSliderPosition: sweetnessSliderPosition,
              #strengthSliderPosition: strengthSliderPosition,
              #brewingMethodId: brewingMethodId,
              #notes: notes,
              #beans: beans,
              #roaster: roaster,
              #rating: rating,
              #coffeeBeansId: coffeeBeansId,
              #isMarked: isMarked,
              #coffeeBeansUuid: coffeeBeansUuid,
              #grindSize: grindSize,
              #tdsPercent: tdsPercent,
              #extractionYieldPercent: extractionYieldPercent,
              #waterTemp: waterTemp,
              #tasteBalance: tasteBalance,
              #entrySource: entrySource,
              #tags: tags,
              #clearBeans: clearBeans,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDiaryAmounts({
    required String? statUuid,
    required double? coffeeAmount,
    required double? waterAmount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryAmounts, [], {
              #statUuid: statUuid,
              #coffeeAmount: coffeeAmount,
              #waterAmount: waterAmount,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDiaryGrindSize({
    required String? statUuid,
    required String? grindSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryGrindSize, [], {
              #statUuid: statUuid,
              #grindSize: grindSize,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDiaryWaterTemperature({
    required String? statUuid,
    required double? waterTemp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryWaterTemperature, [], {
              #statUuid: statUuid,
              #waterTemp: waterTemp,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDiaryTasteBalance({
    required String? statUuid,
    required int? tasteBalance,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryTasteBalance, [], {
              #statUuid: statUuid,
              #tasteBalance: tasteBalance,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDiaryNotes({
    required String? statUuid,
    required String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryNotes, [], {
              #statUuid: statUuid,
              #notes: notes,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDiaryTags({
    required String? statUuid,
    required String? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryTags, [], {
              #statUuid: statUuid,
              #tags: tags,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDiaryRating({
    required String? statUuid,
    required double? rating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryRating, [], {
              #statUuid: statUuid,
              #rating: rating,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDiaryBean({
    required String? statUuid,
    required String? nextBeanUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryBean, [], {
              #statUuid: statUuid,
              #nextBeanUuid: nextBeanUuid,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUserStat(String? statUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserStat, [statUuid]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.UserStatsModel>> fetchAllUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllUserStats, []),
            returnValue: _i6.Future<List<_i10.UserStatsModel>>.value(
              <_i10.UserStatsModel>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i10.UserStatsModel>>.value(
                  <_i10.UserStatsModel>[],
                ),
          )
          as _i6.Future<List<_i10.UserStatsModel>>);

  @override
  _i6.Future<List<_i11.DiaryEntry>> fetchDiaryEntries(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiaryEntries, [locale]),
            returnValue: _i6.Future<List<_i11.DiaryEntry>>.value(
              <_i11.DiaryEntry>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i11.DiaryEntry>>.value(
              <_i11.DiaryEntry>[],
            ),
          )
          as _i6.Future<List<_i11.DiaryEntry>>);

  @override
  _i6.Future<List<({String brewingMethodId, int count, String methodName})>>
  topMethodsLast90Days(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#topMethodsLast90Days, [locale]),
            returnValue:
                _i6.Future<
                  List<({String brewingMethodId, int count, String methodName})>
                >.value(
                  <({String brewingMethodId, int count, String methodName})>[],
                ),
            returnValueForMissingStub:
                _i6.Future<
                  List<({String brewingMethodId, int count, String methodName})>
                >.value(
                  <({String brewingMethodId, int count, String methodName})>[],
                ),
          )
          as _i6.Future<
            List<({String brewingMethodId, int count, String methodName})>
          >);

  @override
  _i6.Future<_i10.UserStatsModel?> fetchUserStatByUuid(String? statUuid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserStatByUuid, [statUuid]),
            returnValue: _i6.Future<_i10.UserStatsModel?>.value(),
            returnValueForMissingStub: _i6.Future<_i10.UserStatsModel?>.value(),
          )
          as _i6.Future<_i10.UserStatsModel?>);

  @override
  _i6.Future<_i2.GrindSuggestionResult?> latestGrindSuggestionForBeanAndMethod(
    String? beansUuid,
    String? brewingMethodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#latestGrindSuggestionForBeanAndMethod, [
              beansUuid,
              brewingMethodId,
            ]),
            returnValue: _i6.Future<_i2.GrindSuggestionResult?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i2.GrindSuggestionResult?>.value(),
          )
          as _i6.Future<_i2.GrindSuggestionResult?>);

  @override
  _i6.Future<List<_i10.UserStatsModel>> fetchStatsByBeanUuid(
    String? beansUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStatsByBeanUuid, [beansUuid]),
            returnValue: _i6.Future<List<_i10.UserStatsModel>>.value(
              <_i10.UserStatsModel>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i10.UserStatsModel>>.value(
                  <_i10.UserStatsModel>[],
                ),
          )
          as _i6.Future<List<_i10.UserStatsModel>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctGrindSizes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctGrindSizes, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> fetchAllDistinctTags() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctTags, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<_i10.UserStatsModel>> fetchRecentStats({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecentStats, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i10.UserStatsModel>>.value(
              <_i10.UserStatsModel>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i10.UserStatsModel>>.value(
                  <_i10.UserStatsModel>[],
                ),
          )
          as _i6.Future<List<_i10.UserStatsModel>>);

  @override
  _i6.Future<int?> estimateBrewsLeft({
    required String? beansUuid,
    required double? packageWeightGrams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#estimateBrewsLeft, [], {
              #beansUuid: beansUuid,
              #packageWeightGrams: packageWeightGrams,
            }),
            returnValue: _i6.Future<int?>.value(),
            returnValueForMissingStub: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<_i10.UserStatsModel?> fetchUserStatById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserStatById, [id]),
            returnValue: _i6.Future<_i10.UserStatsModel?>.value(),
            returnValueForMissingStub: _i6.Future<_i10.UserStatsModel?>.value(),
          )
          as _i6.Future<_i10.UserStatsModel?>);

  @override
  _i6.Future<void> batchUploadUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#batchUploadUserStats, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> batchDownloadUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#batchDownloadUserStats, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#syncUserStats, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUserStatById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserStatById, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<double> fetchBrewedCoffeeAmountForPeriod(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBrewedCoffeeAmountForPeriod, [start, end]),
            returnValue: _i6.Future<double>.value(0.0),
            returnValueForMissingStub: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<List<String>> fetchTopRecipeIdsForPeriod(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRecipeIdsForPeriod, [start, end]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  DateTime getStartOfToday() =>
      (super.noSuchMethod(
            Invocation.method(#getStartOfToday, []),
            returnValue: _FakeDateTime_4(
              this,
              Invocation.method(#getStartOfToday, []),
            ),
            returnValueForMissingStub: _FakeDateTime_4(
              this,
              Invocation.method(#getStartOfToday, []),
            ),
          )
          as DateTime);

  @override
  DateTime getEndOfToday() =>
      (super.noSuchMethod(
            Invocation.method(#getEndOfToday, []),
            returnValue: _FakeDateTime_4(
              this,
              Invocation.method(#getEndOfToday, []),
            ),
            returnValueForMissingStub: _FakeDateTime_4(
              this,
              Invocation.method(#getEndOfToday, []),
            ),
          )
          as DateTime);

  @override
  DateTime getStartOfWeek() =>
      (super.noSuchMethod(
            Invocation.method(#getStartOfWeek, []),
            returnValue: _FakeDateTime_4(
              this,
              Invocation.method(#getStartOfWeek, []),
            ),
            returnValueForMissingStub: _FakeDateTime_4(
              this,
              Invocation.method(#getStartOfWeek, []),
            ),
          )
          as DateTime);

  @override
  DateTime getStartOfMonth() =>
      (super.noSuchMethod(
            Invocation.method(#getStartOfMonth, []),
            returnValue: _FakeDateTime_4(
              this,
              Invocation.method(#getStartOfMonth, []),
            ),
            returnValueForMissingStub: _FakeDateTime_4(
              this,
              Invocation.method(#getStartOfMonth, []),
            ),
          )
          as DateTime);

  @override
  _i6.Future<void> backfillMissingCoffeeBeansUuids() =>
      (super.noSuchMethod(
            Invocation.method(#backfillMissingCoffeeBeansUuids, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> backfillMissingStatUuids() =>
      (super.noSuchMethod(
            Invocation.method(#backfillMissingStatUuids, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncNewUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#syncNewUserStats, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Map<String, dynamic> serializeUserStatForTesting(
    _i10.UserStatsModel? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#serializeUserStatForTesting, [model]),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
