// Mocks generated by Mockito 5.4.6 from annotations
// in coffee_timer/test/unit/widgets/remaining_screen_async_context_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i5;

import 'package:coffee_timer/database/database.dart' as _i2;
import 'package:coffee_timer/models/coffee_beans_model.dart' as _i15;
import 'package:coffee_timer/models/launch_popup_model.dart' as _i13;
import 'package:coffee_timer/models/recipe_model.dart' as _i11;
import 'package:coffee_timer/models/supported_locale_model.dart' as _i14;
import 'package:coffee_timer/providers/coffee_beans_provider.dart' as _i9;
import 'package:coffee_timer/providers/database_provider.dart' as _i3;
import 'package:coffee_timer/providers/recipe_provider.dart' as _i10;
import 'package:coffee_timer/services/analytics_service.dart' as _i16;
import 'package:drift/drift.dart' as _i6;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i7;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseProvider_1 extends _i1.SmartFake
    implements _i3.DatabaseProvider {
  _FakeDatabaseProvider_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_3 extends _i1.SmartFake implements _i5.Locale {
  _FakeLocale_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_4 extends _i1.SmartFake
    implements _i6.MigrationStrategy {
  _FakeMigrationStrategy_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_5 extends _i1.SmartFake
    implements _i2.$AppDatabaseManager {
  _Fake$AppDatabaseManager_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SupportedLocalesTable_6 extends _i1.SmartFake
    implements _i2.$SupportedLocalesTable {
  _Fake$SupportedLocalesTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BrewingMethodsTable_7 extends _i1.SmartFake
    implements _i2.$BrewingMethodsTable {
  _Fake$BrewingMethodsTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecipesTable_8 extends _i1.SmartFake implements _i2.$RecipesTable {
  _Fake$RecipesTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecipeLocalizationsTable_9 extends _i1.SmartFake
    implements _i2.$RecipeLocalizationsTable {
  _Fake$RecipeLocalizationsTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$StepsTable_10 extends _i1.SmartFake implements _i2.$StepsTable {
  _Fake$StepsTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserRecipePreferencesTable_11 extends _i1.SmartFake
    implements _i2.$UserRecipePreferencesTable {
  _Fake$UserRecipePreferencesTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$CoffeeFactsTable_12 extends _i1.SmartFake
    implements _i2.$CoffeeFactsTable {
  _Fake$CoffeeFactsTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserStatsTable_13 extends _i1.SmartFake
    implements _i2.$UserStatsTable {
  _Fake$UserStatsTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CoffeeBeansTable_14 extends _i1.SmartFake
    implements _i2.$CoffeeBeansTable {
  _Fake$CoffeeBeansTable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecipeCollectionsTable_15 extends _i1.SmartFake
    implements _i2.$RecipeCollectionsTable {
  _Fake$RecipeCollectionsTable_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecipeCollectionLocalizationsTable_16 extends _i1.SmartFake
    implements _i2.$RecipeCollectionLocalizationsTable {
  _Fake$RecipeCollectionLocalizationsTable_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$RecipeCollectionMembersTable_17 extends _i1.SmartFake
    implements _i2.$RecipeCollectionMembersTable {
  _Fake$RecipeCollectionMembersTable_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$HelpCategoriesTable_18 extends _i1.SmartFake
    implements _i2.$HelpCategoriesTable {
  _Fake$HelpCategoriesTable_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$HelpArticlesTable_19 extends _i1.SmartFake
    implements _i2.$HelpArticlesTable {
  _Fake$HelpArticlesTable_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIndex_20 extends _i1.SmartFake implements _i6.Index {
  _FakeIndex_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipesDao_21 extends _i1.SmartFake implements _i2.RecipesDao {
  _FakeRecipesDao_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStepsDao_22 extends _i1.SmartFake implements _i2.StepsDao {
  _FakeStepsDao_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipeLocalizationsDao_23 extends _i1.SmartFake
    implements _i2.RecipeLocalizationsDao {
  _FakeRecipeLocalizationsDao_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserRecipePreferencesDao_24 extends _i1.SmartFake
    implements _i2.UserRecipePreferencesDao {
  _FakeUserRecipePreferencesDao_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBrewingMethodsDao_25 extends _i1.SmartFake
    implements _i2.BrewingMethodsDao {
  _FakeBrewingMethodsDao_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupportedLocalesDao_26 extends _i1.SmartFake
    implements _i2.SupportedLocalesDao {
  _FakeSupportedLocalesDao_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCoffeeFactsDao_27 extends _i1.SmartFake
    implements _i2.CoffeeFactsDao {
  _FakeCoffeeFactsDao_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserStatsDao_28 extends _i1.SmartFake implements _i2.UserStatsDao {
  _FakeUserStatsDao_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCoffeeBeansDao_29 extends _i1.SmartFake
    implements _i2.CoffeeBeansDao {
  _FakeCoffeeBeansDao_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBeansStatsDao_30 extends _i1.SmartFake implements _i2.BeansStatsDao {
  _FakeBeansStatsDao_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipeCollectionsDao_31 extends _i1.SmartFake
    implements _i2.RecipeCollectionsDao {
  _FakeRecipeCollectionsDao_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHelpDao_32 extends _i1.SmartFake implements _i2.HelpDao {
  _FakeHelpDao_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_33 extends _i1.SmartFake
    implements _i6.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_34 extends _i1.SmartFake
    implements _i6.GeneratedDatabase {
  _FakeGeneratedDatabase_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_35 extends _i1.SmartFake
    implements _i6.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_36 extends _i1.SmartFake
    implements _i6.DatabaseConnection {
  _FakeDatabaseConnection_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_37 extends _i1.SmartFake implements _i6.QueryExecutor {
  _FakeQueryExecutor_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_38 extends _i1.SmartFake
    implements _i7.StreamQueryStore {
  _FakeStreamQueryStore_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_39 extends _i1.SmartFake
    implements _i6.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_40 extends _i1.SmartFake implements _i6.Migrator {
  _FakeMigrator_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_41<T> extends _i1.SmartFake implements _i8.Future<T> {
  _FakeFuture_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_42<T1 extends _i6.Table, D1> extends _i1.SmartFake
    implements _i6.InsertStatement<T1, D1> {
  _FakeInsertStatement_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_43<T extends _i6.Table, D> extends _i1.SmartFake
    implements _i6.UpdateStatement<T, D> {
  _FakeUpdateStatement_43(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_44<T1 extends _i6.HasResultSet, D>
    extends _i1.SmartFake
    implements _i6.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_44(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_45<FirstT extends _i6.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i6.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_45(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_46<Row> extends _i1.SmartFake
    implements _i6.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_46(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_47<T1 extends _i6.Table, D1> extends _i1.SmartFake
    implements _i6.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_47(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_48<T> extends _i1.SmartFake implements _i6.Selectable<T> {
  _FakeSelectable_48(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_49 extends _i1.SmartFake
    implements _i6.GenerationContext {
  _FakeGenerationContext_49(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBeanWeightAdjustmentResult_50 extends _i1.SmartFake
    implements _i9.BeanWeightAdjustmentResult {
  _FakeBeanWeightAdjustmentResult_50(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecipeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeProvider extends _i1.Mock implements _i10.RecipeProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseProvider get databaseProvider =>
      (super.noSuchMethod(
            Invocation.getter(#databaseProvider),
            returnValue: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
            returnValueForMissingStub: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
          )
          as _i3.DatabaseProvider);

  @override
  List<_i11.RecipeModel> get recipes =>
      (super.noSuchMethod(
            Invocation.getter(#recipes),
            returnValue: <_i11.RecipeModel>[],
            returnValueForMissingStub: <_i11.RecipeModel>[],
          )
          as List<_i11.RecipeModel>);

  @override
  _i4.ValueNotifier<Set<String>> get shownBrewingMethodIds =>
      (super.noSuchMethod(
            Invocation.getter(#shownBrewingMethodIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#shownBrewingMethodIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#shownBrewingMethodIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  _i4.ValueNotifier<Set<String>> get hiddenBrewingMethodIds =>
      (super.noSuchMethod(
            Invocation.getter(#hiddenBrewingMethodIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#hiddenBrewingMethodIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#hiddenBrewingMethodIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  _i5.Locale get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _FakeLocale_3(this, Invocation.getter(#currentLocale)),
            returnValueForMissingStub: _FakeLocale_3(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as _i5.Locale);

  @override
  _i4.ValueNotifier<Set<String>> get favoriteRecipeIds =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteRecipeIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#favoriteRecipeIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#favoriteRecipeIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> ensureDataReady() =>
      (super.noSuchMethod(
            Invocation.method(#ensureDataReady, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setUserBrewingMethodPreference(
    String? methodId,
    bool? show,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setUserBrewingMethodPreference, [
              methodId,
              show,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchAllRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllRecipes, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i11.RecipeModel>> fetchRecipesForBrewingMethod(
    String? brewingMethodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecipesForBrewingMethod, [brewingMethodId]),
            returnValue: _i8.Future<List<_i11.RecipeModel>>.value(
              <_i11.RecipeModel>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i11.RecipeModel>>.value(
              <_i11.RecipeModel>[],
            ),
          )
          as _i8.Future<List<_i11.RecipeModel>>);

  @override
  _i8.Future<String> getBrewingMethodName(String? brewingMethodId) =>
      (super.noSuchMethod(
            Invocation.method(#getBrewingMethodName, [brewingMethodId]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getBrewingMethodName, [brewingMethodId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getBrewingMethodName, [brewingMethodId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i11.RecipeModel?> getRecipeById(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [recipeId]),
            returnValue: _i8.Future<_i11.RecipeModel?>.value(),
            returnValueForMissingStub: _i8.Future<_i11.RecipeModel?>.value(),
          )
          as _i8.Future<_i11.RecipeModel?>);

  @override
  _i8.Future<void> toggleFavorite(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [recipeId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveCustomAmounts(
    String? recipeId,
    double? coffeeAmount,
    double? waterAmount, {
    String? customGrindSize,
    double? customWaterTemp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveCustomAmounts,
              [recipeId, coffeeAmount, waterAmount],
              {
                #customGrindSize: customGrindSize,
                #customWaterTemp: customWaterTemp,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveSliderPositions(
    String? recipeId, {
    int? sweetnessSliderPosition,
    int? strengthSliderPosition,
    int? coffeeChroniclerSliderPosition,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveSliderPositions,
              [recipeId],
              {
                #sweetnessSliderPosition: sweetnessSliderPosition,
                #strengthSliderPosition: strengthSliderPosition,
                #coffeeChroniclerSliderPosition: coffeeChroniclerSliderPosition,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i11.RecipeModel?> getLastUsedRecipe() =>
      (super.noSuchMethod(
            Invocation.method(#getLastUsedRecipe, []),
            returnValue: _i8.Future<_i11.RecipeModel?>.value(),
            returnValueForMissingStub: _i8.Future<_i11.RecipeModel?>.value(),
          )
          as _i8.Future<_i11.RecipeModel?>);

  @override
  _i8.Future<String> fetchBrewingMethodName(String? brewingMethodId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  List<_i11.RecipeModel> getFavoriteRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteRecipes, []),
            returnValue: <_i11.RecipeModel>[],
            returnValueForMissingStub: <_i11.RecipeModel>[],
          )
          as List<_i11.RecipeModel>);

  @override
  _i8.Future<List<_i11.RecipeModel>> fetchFavoriteRecipes(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFavoriteRecipes, [locale]),
            returnValue: _i8.Future<List<_i11.RecipeModel>>.value(
              <_i11.RecipeModel>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i11.RecipeModel>>.value(
              <_i11.RecipeModel>[],
            ),
          )
          as _i8.Future<List<_i11.RecipeModel>>);

  @override
  _i8.Future<List<_i11.RecipeModel>> fetchRecipesForVendor(String? vendorId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecipesForVendor, [vendorId]),
            returnValue: _i8.Future<List<_i11.RecipeModel>>.value(
              <_i11.RecipeModel>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i11.RecipeModel>>.value(
              <_i11.RecipeModel>[],
            ),
          )
          as _i8.Future<List<_i11.RecipeModel>>);

  @override
  _i8.Future<_i13.LaunchPopupModel?> fetchLatestLaunchPopup(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLatestLaunchPopup, [locale]),
            returnValue: _i8.Future<_i13.LaunchPopupModel?>.value(),
            returnValueForMissingStub:
                _i8.Future<_i13.LaunchPopupModel?>.value(),
          )
          as _i8.Future<_i13.LaunchPopupModel?>);

  @override
  _i8.Future<List<_i14.SupportedLocaleModel>> fetchAllSupportedLocales() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllSupportedLocales, []),
            returnValue: _i8.Future<List<_i14.SupportedLocaleModel>>.value(
              <_i14.SupportedLocaleModel>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i14.SupportedLocaleModel>>.value(
                  <_i14.SupportedLocaleModel>[],
                ),
          )
          as _i8.Future<List<_i14.SupportedLocaleModel>>);

  @override
  _i8.Future<String> getLocaleName(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#getLocaleName, [localeCode]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getLocaleName, [localeCode]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getLocaleName, [localeCode]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> setLocale(_i5.Locale? newLocale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [newLocale]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> getRandomCoffeeFactFromDB() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomCoffeeFactFromDB, []),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getRandomCoffeeFactFromDB, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getRandomCoffeeFactFromDB, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getLocalizedRecipeName(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalizedRecipeName, [recipeId]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getLocalizedRecipeName, [recipeId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getLocalizedRecipeName, [recipeId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<String>> fetchAllDistinctRoasters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoasters, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctBeans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctBeans, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> searchRoasters(String? filter) =>
      (super.noSuchMethod(
            Invocation.method(#searchRoasters, [filter]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> searchBeans(String? filter) =>
      (super.noSuchMethod(
            Invocation.method(#searchBeans, [filter]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i2.AppDatabase {
  @override
  bool get enableForeignKeyConstraints =>
      (super.noSuchMethod(
            Invocation.getter(#enableForeignKeyConstraints),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get schemaVersion =>
      (super.noSuchMethod(
            Invocation.getter(#schemaVersion),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i6.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_4(
              this,
              Invocation.getter(#migration),
            ),
            returnValueForMissingStub: _FakeMigrationStrategy_4(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i6.MigrationStrategy);

  @override
  _i2.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_5(
              this,
              Invocation.getter(#managers),
            ),
            returnValueForMissingStub: _Fake$AppDatabaseManager_5(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i2.$AppDatabaseManager);

  @override
  _i2.$SupportedLocalesTable get supportedLocales =>
      (super.noSuchMethod(
            Invocation.getter(#supportedLocales),
            returnValue: _Fake$SupportedLocalesTable_6(
              this,
              Invocation.getter(#supportedLocales),
            ),
            returnValueForMissingStub: _Fake$SupportedLocalesTable_6(
              this,
              Invocation.getter(#supportedLocales),
            ),
          )
          as _i2.$SupportedLocalesTable);

  @override
  _i2.$BrewingMethodsTable get brewingMethods =>
      (super.noSuchMethod(
            Invocation.getter(#brewingMethods),
            returnValue: _Fake$BrewingMethodsTable_7(
              this,
              Invocation.getter(#brewingMethods),
            ),
            returnValueForMissingStub: _Fake$BrewingMethodsTable_7(
              this,
              Invocation.getter(#brewingMethods),
            ),
          )
          as _i2.$BrewingMethodsTable);

  @override
  _i2.$RecipesTable get recipes =>
      (super.noSuchMethod(
            Invocation.getter(#recipes),
            returnValue: _Fake$RecipesTable_8(
              this,
              Invocation.getter(#recipes),
            ),
            returnValueForMissingStub: _Fake$RecipesTable_8(
              this,
              Invocation.getter(#recipes),
            ),
          )
          as _i2.$RecipesTable);

  @override
  _i2.$RecipeLocalizationsTable get recipeLocalizations =>
      (super.noSuchMethod(
            Invocation.getter(#recipeLocalizations),
            returnValue: _Fake$RecipeLocalizationsTable_9(
              this,
              Invocation.getter(#recipeLocalizations),
            ),
            returnValueForMissingStub: _Fake$RecipeLocalizationsTable_9(
              this,
              Invocation.getter(#recipeLocalizations),
            ),
          )
          as _i2.$RecipeLocalizationsTable);

  @override
  _i2.$StepsTable get steps =>
      (super.noSuchMethod(
            Invocation.getter(#steps),
            returnValue: _Fake$StepsTable_10(this, Invocation.getter(#steps)),
            returnValueForMissingStub: _Fake$StepsTable_10(
              this,
              Invocation.getter(#steps),
            ),
          )
          as _i2.$StepsTable);

  @override
  _i2.$UserRecipePreferencesTable get userRecipePreferences =>
      (super.noSuchMethod(
            Invocation.getter(#userRecipePreferences),
            returnValue: _Fake$UserRecipePreferencesTable_11(
              this,
              Invocation.getter(#userRecipePreferences),
            ),
            returnValueForMissingStub: _Fake$UserRecipePreferencesTable_11(
              this,
              Invocation.getter(#userRecipePreferences),
            ),
          )
          as _i2.$UserRecipePreferencesTable);

  @override
  _i2.$CoffeeFactsTable get coffeeFacts =>
      (super.noSuchMethod(
            Invocation.getter(#coffeeFacts),
            returnValue: _Fake$CoffeeFactsTable_12(
              this,
              Invocation.getter(#coffeeFacts),
            ),
            returnValueForMissingStub: _Fake$CoffeeFactsTable_12(
              this,
              Invocation.getter(#coffeeFacts),
            ),
          )
          as _i2.$CoffeeFactsTable);

  @override
  _i2.$UserStatsTable get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: _Fake$UserStatsTable_13(
              this,
              Invocation.getter(#userStats),
            ),
            returnValueForMissingStub: _Fake$UserStatsTable_13(
              this,
              Invocation.getter(#userStats),
            ),
          )
          as _i2.$UserStatsTable);

  @override
  _i2.$CoffeeBeansTable get coffeeBeans =>
      (super.noSuchMethod(
            Invocation.getter(#coffeeBeans),
            returnValue: _Fake$CoffeeBeansTable_14(
              this,
              Invocation.getter(#coffeeBeans),
            ),
            returnValueForMissingStub: _Fake$CoffeeBeansTable_14(
              this,
              Invocation.getter(#coffeeBeans),
            ),
          )
          as _i2.$CoffeeBeansTable);

  @override
  _i2.$RecipeCollectionsTable get recipeCollections =>
      (super.noSuchMethod(
            Invocation.getter(#recipeCollections),
            returnValue: _Fake$RecipeCollectionsTable_15(
              this,
              Invocation.getter(#recipeCollections),
            ),
            returnValueForMissingStub: _Fake$RecipeCollectionsTable_15(
              this,
              Invocation.getter(#recipeCollections),
            ),
          )
          as _i2.$RecipeCollectionsTable);

  @override
  _i2.$RecipeCollectionLocalizationsTable get recipeCollectionLocalizations =>
      (super.noSuchMethod(
            Invocation.getter(#recipeCollectionLocalizations),
            returnValue: _Fake$RecipeCollectionLocalizationsTable_16(
              this,
              Invocation.getter(#recipeCollectionLocalizations),
            ),
            returnValueForMissingStub:
                _Fake$RecipeCollectionLocalizationsTable_16(
                  this,
                  Invocation.getter(#recipeCollectionLocalizations),
                ),
          )
          as _i2.$RecipeCollectionLocalizationsTable);

  @override
  _i2.$RecipeCollectionMembersTable get recipeCollectionMembers =>
      (super.noSuchMethod(
            Invocation.getter(#recipeCollectionMembers),
            returnValue: _Fake$RecipeCollectionMembersTable_17(
              this,
              Invocation.getter(#recipeCollectionMembers),
            ),
            returnValueForMissingStub: _Fake$RecipeCollectionMembersTable_17(
              this,
              Invocation.getter(#recipeCollectionMembers),
            ),
          )
          as _i2.$RecipeCollectionMembersTable);

  @override
  _i2.$HelpCategoriesTable get helpCategories =>
      (super.noSuchMethod(
            Invocation.getter(#helpCategories),
            returnValue: _Fake$HelpCategoriesTable_18(
              this,
              Invocation.getter(#helpCategories),
            ),
            returnValueForMissingStub: _Fake$HelpCategoriesTable_18(
              this,
              Invocation.getter(#helpCategories),
            ),
          )
          as _i2.$HelpCategoriesTable);

  @override
  _i2.$HelpArticlesTable get helpArticles =>
      (super.noSuchMethod(
            Invocation.getter(#helpArticles),
            returnValue: _Fake$HelpArticlesTable_19(
              this,
              Invocation.getter(#helpArticles),
            ),
            returnValueForMissingStub: _Fake$HelpArticlesTable_19(
              this,
              Invocation.getter(#helpArticles),
            ),
          )
          as _i2.$HelpArticlesTable);

  @override
  _i6.Index get idxRecipesLastModified =>
      (super.noSuchMethod(
            Invocation.getter(#idxRecipesLastModified),
            returnValue: _FakeIndex_20(
              this,
              Invocation.getter(#idxRecipesLastModified),
            ),
            returnValueForMissingStub: _FakeIndex_20(
              this,
              Invocation.getter(#idxRecipesLastModified),
            ),
          )
          as _i6.Index);

  @override
  _i6.Index get idxUserStatsStatUuidVersionVector =>
      (super.noSuchMethod(
            Invocation.getter(#idxUserStatsStatUuidVersionVector),
            returnValue: _FakeIndex_20(
              this,
              Invocation.getter(#idxUserStatsStatUuidVersionVector),
            ),
            returnValueForMissingStub: _FakeIndex_20(
              this,
              Invocation.getter(#idxUserStatsStatUuidVersionVector),
            ),
          )
          as _i6.Index);

  @override
  _i6.Index get idxCoffeeBeansBeansUuidVersionVector =>
      (super.noSuchMethod(
            Invocation.getter(#idxCoffeeBeansBeansUuidVersionVector),
            returnValue: _FakeIndex_20(
              this,
              Invocation.getter(#idxCoffeeBeansBeansUuidVersionVector),
            ),
            returnValueForMissingStub: _FakeIndex_20(
              this,
              Invocation.getter(#idxCoffeeBeansBeansUuidVersionVector),
            ),
          )
          as _i6.Index);

  @override
  _i2.RecipesDao get recipesDao =>
      (super.noSuchMethod(
            Invocation.getter(#recipesDao),
            returnValue: _FakeRecipesDao_21(
              this,
              Invocation.getter(#recipesDao),
            ),
            returnValueForMissingStub: _FakeRecipesDao_21(
              this,
              Invocation.getter(#recipesDao),
            ),
          )
          as _i2.RecipesDao);

  @override
  _i2.StepsDao get stepsDao =>
      (super.noSuchMethod(
            Invocation.getter(#stepsDao),
            returnValue: _FakeStepsDao_22(this, Invocation.getter(#stepsDao)),
            returnValueForMissingStub: _FakeStepsDao_22(
              this,
              Invocation.getter(#stepsDao),
            ),
          )
          as _i2.StepsDao);

  @override
  _i2.RecipeLocalizationsDao get recipeLocalizationsDao =>
      (super.noSuchMethod(
            Invocation.getter(#recipeLocalizationsDao),
            returnValue: _FakeRecipeLocalizationsDao_23(
              this,
              Invocation.getter(#recipeLocalizationsDao),
            ),
            returnValueForMissingStub: _FakeRecipeLocalizationsDao_23(
              this,
              Invocation.getter(#recipeLocalizationsDao),
            ),
          )
          as _i2.RecipeLocalizationsDao);

  @override
  _i2.UserRecipePreferencesDao get userRecipePreferencesDao =>
      (super.noSuchMethod(
            Invocation.getter(#userRecipePreferencesDao),
            returnValue: _FakeUserRecipePreferencesDao_24(
              this,
              Invocation.getter(#userRecipePreferencesDao),
            ),
            returnValueForMissingStub: _FakeUserRecipePreferencesDao_24(
              this,
              Invocation.getter(#userRecipePreferencesDao),
            ),
          )
          as _i2.UserRecipePreferencesDao);

  @override
  _i2.BrewingMethodsDao get brewingMethodsDao =>
      (super.noSuchMethod(
            Invocation.getter(#brewingMethodsDao),
            returnValue: _FakeBrewingMethodsDao_25(
              this,
              Invocation.getter(#brewingMethodsDao),
            ),
            returnValueForMissingStub: _FakeBrewingMethodsDao_25(
              this,
              Invocation.getter(#brewingMethodsDao),
            ),
          )
          as _i2.BrewingMethodsDao);

  @override
  _i2.SupportedLocalesDao get supportedLocalesDao =>
      (super.noSuchMethod(
            Invocation.getter(#supportedLocalesDao),
            returnValue: _FakeSupportedLocalesDao_26(
              this,
              Invocation.getter(#supportedLocalesDao),
            ),
            returnValueForMissingStub: _FakeSupportedLocalesDao_26(
              this,
              Invocation.getter(#supportedLocalesDao),
            ),
          )
          as _i2.SupportedLocalesDao);

  @override
  _i2.CoffeeFactsDao get coffeeFactsDao =>
      (super.noSuchMethod(
            Invocation.getter(#coffeeFactsDao),
            returnValue: _FakeCoffeeFactsDao_27(
              this,
              Invocation.getter(#coffeeFactsDao),
            ),
            returnValueForMissingStub: _FakeCoffeeFactsDao_27(
              this,
              Invocation.getter(#coffeeFactsDao),
            ),
          )
          as _i2.CoffeeFactsDao);

  @override
  _i2.UserStatsDao get userStatsDao =>
      (super.noSuchMethod(
            Invocation.getter(#userStatsDao),
            returnValue: _FakeUserStatsDao_28(
              this,
              Invocation.getter(#userStatsDao),
            ),
            returnValueForMissingStub: _FakeUserStatsDao_28(
              this,
              Invocation.getter(#userStatsDao),
            ),
          )
          as _i2.UserStatsDao);

  @override
  _i2.CoffeeBeansDao get coffeeBeansDao =>
      (super.noSuchMethod(
            Invocation.getter(#coffeeBeansDao),
            returnValue: _FakeCoffeeBeansDao_29(
              this,
              Invocation.getter(#coffeeBeansDao),
            ),
            returnValueForMissingStub: _FakeCoffeeBeansDao_29(
              this,
              Invocation.getter(#coffeeBeansDao),
            ),
          )
          as _i2.CoffeeBeansDao);

  @override
  _i2.BeansStatsDao get beansStatsDao =>
      (super.noSuchMethod(
            Invocation.getter(#beansStatsDao),
            returnValue: _FakeBeansStatsDao_30(
              this,
              Invocation.getter(#beansStatsDao),
            ),
            returnValueForMissingStub: _FakeBeansStatsDao_30(
              this,
              Invocation.getter(#beansStatsDao),
            ),
          )
          as _i2.BeansStatsDao);

  @override
  _i2.RecipeCollectionsDao get recipeCollectionsDao =>
      (super.noSuchMethod(
            Invocation.getter(#recipeCollectionsDao),
            returnValue: _FakeRecipeCollectionsDao_31(
              this,
              Invocation.getter(#recipeCollectionsDao),
            ),
            returnValueForMissingStub: _FakeRecipeCollectionsDao_31(
              this,
              Invocation.getter(#recipeCollectionsDao),
            ),
          )
          as _i2.RecipeCollectionsDao);

  @override
  _i2.HelpDao get helpDao =>
      (super.noSuchMethod(
            Invocation.getter(#helpDao),
            returnValue: _FakeHelpDao_32(this, Invocation.getter(#helpDao)),
            returnValueForMissingStub: _FakeHelpDao_32(
              this,
              Invocation.getter(#helpDao),
            ),
          )
          as _i2.HelpDao);

  @override
  Iterable<_i6.TableInfo<_i6.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i6.TableInfo<_i6.Table, Object?>>[],
            returnValueForMissingStub: <_i6.TableInfo<_i6.Table, Object?>>[],
          )
          as Iterable<_i6.TableInfo<_i6.Table, Object?>>);

  @override
  List<_i6.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i6.DatabaseSchemaEntity>[],
            returnValueForMissingStub: <_i6.DatabaseSchemaEntity>[],
          )
          as List<_i6.DatabaseSchemaEntity>);

  @override
  _i6.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_33(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
            returnValueForMissingStub: _FakeStreamQueryUpdateRules_33(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i6.StreamQueryUpdateRules);

  @override
  _i6.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_34(
              this,
              Invocation.getter(#attachedDatabase),
            ),
            returnValueForMissingStub: _FakeGeneratedDatabase_34(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i6.GeneratedDatabase);

  @override
  _i6.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_35(
              this,
              Invocation.getter(#options),
            ),
            returnValueForMissingStub: _FakeDriftDatabaseOptions_35(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i6.DriftDatabaseOptions);

  @override
  _i6.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_36(
              this,
              Invocation.getter(#connection),
            ),
            returnValueForMissingStub: _FakeDatabaseConnection_36(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i6.DatabaseConnection);

  @override
  _i6.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i12.dummyValue<_i6.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
            returnValueForMissingStub: _i12.dummyValue<_i6.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i6.SqlTypes);

  @override
  _i6.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_37(
              this,
              Invocation.getter(#executor),
            ),
            returnValueForMissingStub: _FakeQueryExecutor_37(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i6.QueryExecutor);

  @override
  _i7.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_38(
              this,
              Invocation.getter(#streamQueries),
            ),
            returnValueForMissingStub: _FakeStreamQueryStore_38(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i7.StreamQueryStore);

  @override
  _i6.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_39(
              this,
              Invocation.getter(#resolvedEngine),
            ),
            returnValueForMissingStub: _FakeDatabaseConnectionUser_39(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i6.DatabaseConnectionUser);

  @override
  _i6.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_40(
              this,
              Invocation.method(#createMigrator, []),
            ),
            returnValueForMissingStub: _FakeMigrator_40(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i6.Migrator);

  @override
  _i8.Future<void> beforeOpen(
    _i6.QueryExecutor? executor,
    _i6.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Ret> computeWithDatabase<Ret, DB extends _i6.GeneratedDatabase>({
    required _i8.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i6.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i8.Future<Ret>.value(v),
                ) ??
                _FakeFuture_41<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
            returnValueForMissingStub:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i8.Future<Ret>.value(v),
                ) ??
                _FakeFuture_41<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i8.Future<Ret>);

  @override
  _i8.Stream<T> createStream<T extends Object>(
    _i7.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i8.Stream<T>.empty(),
            returnValueForMissingStub: _i8.Stream<T>.empty(),
          )
          as _i8.Stream<T>);

  @override
  T alias<T, D>(_i6.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i12.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
            returnValueForMissingStub: _i12.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i6.TableInfo<_i6.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i6.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Stream<Set<_i6.TableUpdate>> tableUpdates([
    _i6.TableUpdateQuery? query = const _i6.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i8.Stream<Set<_i6.TableUpdate>>.empty(),
            returnValueForMissingStub: _i8.Stream<Set<_i6.TableUpdate>>.empty(),
          )
          as _i8.Stream<Set<_i6.TableUpdate>>);

  @override
  _i8.Future<T> doWhenOpened<T>(
    _i8.FutureOr<T> Function(_i6.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_41<T>(this, Invocation.method(#doWhenOpened, [fn])),
            returnValueForMissingStub:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_41<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i8.Future<T>);

  @override
  _i6.InsertStatement<T, D> into<T extends _i6.Table, D>(
    _i6.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_42<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
            returnValueForMissingStub: _FakeInsertStatement_42<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i6.InsertStatement<T, D>);

  @override
  _i6.UpdateStatement<Tbl, R> update<Tbl extends _i6.Table, R>(
    _i6.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_43<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
            returnValueForMissingStub: _FakeUpdateStatement_43<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i6.UpdateStatement<Tbl, R>);

  @override
  _i6.SimpleSelectStatement<T, R> select<T extends _i6.HasResultSet, R>(
    _i6.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_44<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeSimpleSelectStatement_44<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i6.SimpleSelectStatement<T, R>);

  @override
  _i6.JoinedSelectStatement<T, R> selectOnly<T extends _i6.HasResultSet, R>(
    _i6.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_45<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeJoinedSelectStatement_45<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i6.JoinedSelectStatement<T, R>);

  @override
  _i6.BaseSelectStatement<_i6.TypedResult> selectExpressions(
    Iterable<_i6.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_46<_i6.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
            returnValueForMissingStub:
                _FakeBaseSelectStatement_46<_i6.TypedResult>(
                  this,
                  Invocation.method(#selectExpressions, [columns]),
                ),
          )
          as _i6.BaseSelectStatement<_i6.TypedResult>);

  @override
  _i6.DeleteStatement<T, D> delete<T extends _i6.Table, D>(
    _i6.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_47<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
            returnValueForMissingStub: _FakeDeleteStatement_47<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i6.DeleteStatement<T, D>);

  @override
  _i8.Future<int> customUpdate(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i6.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> customInsert(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i6.QueryRow>> customWriteReturning(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i6.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i8.Future<List<_i6.QueryRow>>.value(<_i6.QueryRow>[]),
            returnValueForMissingStub: _i8.Future<List<_i6.QueryRow>>.value(
              <_i6.QueryRow>[],
            ),
          )
          as _i8.Future<List<_i6.QueryRow>>);

  @override
  _i6.Selectable<_i6.QueryRow> customSelect(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_48<_i6.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_48<_i6.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i6.Selectable<_i6.QueryRow>);

  @override
  _i6.Selectable<_i6.QueryRow> customSelectQuery(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_48<_i6.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_48<_i6.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i6.Selectable<_i6.QueryRow>);

  @override
  _i8.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<T> transaction<T>(
    _i8.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_41<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
            returnValueForMissingStub:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_41<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<T> exclusively<T>(_i8.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_41<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
            returnValueForMissingStub:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_41<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<void> batch(_i8.FutureOr<void> Function(_i6.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<T> runWithInterceptor<T>(
    _i8.Future<T> Function()? action, {
    required _i6.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_41<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
            returnValueForMissingStub:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_41<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i8.Future<T>);

  @override
  _i6.GenerationContext $write(
    _i6.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_49(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_49(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i6.GenerationContext);

  @override
  _i6.GenerationContext $writeInsertable(
    _i6.TableInfo<_i6.Table, dynamic>? table,
    _i6.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_49(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_49(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i6.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [CoffeeBeansProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoffeeBeansProvider extends _i1.Mock
    implements _i9.CoffeeBeansProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseProvider get databaseProvider =>
      (super.noSuchMethod(
            Invocation.getter(#databaseProvider),
            returnValue: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
            returnValueForMissingStub: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
          )
          as _i3.DatabaseProvider);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateCacheEntry(
    String? dataType,
    String? locale, {
    bool? isLocaleAgnostic = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #invalidateCacheEntry,
      [dataType, locale],
      {#isLocaleAgnostic: isLocaleAgnostic},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateDataType(String? dataType, {bool? isLocaleAgnostic = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #invalidateDataType,
          [dataType],
          {#isLocaleAgnostic: isLocaleAgnostic},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateExpiredEntries() => super.noSuchMethod(
    Invocation.method(#invalidateExpiredEntries, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> refreshDataType(
    String? dataType,
    String? locale, {
    bool? prefetch = false,
    bool? isLocaleAgnostic = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #refreshDataType,
              [dataType, locale],
              {#prefetch: prefetch, #isLocaleAgnostic: isLocaleAgnostic},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i15.CoffeeBeansModel>> fetchAllCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllCoffeeBeans, []),
            returnValue: _i8.Future<List<_i15.CoffeeBeansModel>>.value(
              <_i15.CoffeeBeansModel>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i15.CoffeeBeansModel>>.value(
                  <_i15.CoffeeBeansModel>[],
                ),
          )
          as _i8.Future<List<_i15.CoffeeBeansModel>>);

  @override
  _i8.Future<String> addCoffeeBeans(_i15.CoffeeBeansModel? beans) =>
      (super.noSuchMethod(
            Invocation.method(#addCoffeeBeans, [beans]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#addCoffeeBeans, [beans]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#addCoffeeBeans, [beans]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> updateCoffeeBeans(_i15.CoffeeBeansModel? beans) =>
      (super.noSuchMethod(
            Invocation.method(#updateCoffeeBeans, [beans]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCoffeeBeans(String? beansUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCoffeeBeans, [beansUuid]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i15.CoffeeBeansModel?> fetchCoffeeBeansById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCoffeeBeansById, [id]),
            returnValue: _i8.Future<_i15.CoffeeBeansModel?>.value(),
            returnValueForMissingStub:
                _i8.Future<_i15.CoffeeBeansModel?>.value(),
          )
          as _i8.Future<_i15.CoffeeBeansModel?>);

  @override
  _i8.Future<_i15.CoffeeBeansModel?> fetchCoffeeBeansByUuid(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCoffeeBeansByUuid, [uuid]),
            returnValue: _i8.Future<_i15.CoffeeBeansModel?>.value(),
            returnValueForMissingStub:
                _i8.Future<_i15.CoffeeBeansModel?>.value(),
          )
          as _i8.Future<_i15.CoffeeBeansModel?>);

  @override
  _i8.Future<List<String>> fetchAllDistinctRoasters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoasters, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctNames() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctNames, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctVarieties() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctVarieties, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctProcessingMethods() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctProcessingMethods, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctRoastLevels() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoastLevels, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctOrigins() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctOrigins, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctTastingNotes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctTastingNotes, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctRegions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRegions, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctFarmers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctFarmers, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctFarms() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctFarms, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctGrindSizes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctGrindSizes, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchCombinedTastingNotes(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedTastingNotes, [locale]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchCombinedOrigins(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedOrigins, [locale]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchCombinedProcessingMethods(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedProcessingMethods, [locale]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchCombinedRoasters(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedRoasters, [locale]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> toggleFavoriteStatus(String? uuid, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteStatus, [uuid, isFavorite]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> backfillMissingUuids() =>
      (super.noSuchMethod(
            Invocation.method(#backfillMissingUuids, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> batchUploadCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#batchUploadCoffeeBeans, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> batchDownloadCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#batchDownloadCoffeeBeans, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> syncCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#syncCoffeeBeans, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> syncNewCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#syncNewCoffeeBeans, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i15.CoffeeBeansModel>> fetchFilteredCoffeeBeans({
    List<String>? roasters,
    List<String>? origins,
    bool? isFavorite,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFilteredCoffeeBeans, [], {
              #roasters: roasters,
              #origins: origins,
              #isFavorite: isFavorite,
            }),
            returnValue: _i8.Future<List<_i15.CoffeeBeansModel>>.value(
              <_i15.CoffeeBeansModel>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i15.CoffeeBeansModel>>.value(
                  <_i15.CoffeeBeansModel>[],
                ),
          )
          as _i8.Future<List<_i15.CoffeeBeansModel>>);

  @override
  _i8.Future<List<String>> fetchOriginsForRoasters(
    List<String>? selectedRoasters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOriginsForRoasters, [selectedRoasters]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<_i9.BeanWeightAdjustmentResult> adjustBeanWeightForDoseDelta(
    String? beansUuid,
    double? doseDelta,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#adjustBeanWeightForDoseDelta, [
              beansUuid,
              doseDelta,
            ]),
            returnValue: _i8.Future<_i9.BeanWeightAdjustmentResult>.value(
              _FakeBeanWeightAdjustmentResult_50(
                this,
                Invocation.method(#adjustBeanWeightForDoseDelta, [
                  beansUuid,
                  doseDelta,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i9.BeanWeightAdjustmentResult>.value(
                  _FakeBeanWeightAdjustmentResult_50(
                    this,
                    Invocation.method(#adjustBeanWeightForDoseDelta, [
                      beansUuid,
                      doseDelta,
                    ]),
                  ),
                ),
          )
          as _i8.Future<_i9.BeanWeightAdjustmentResult>);

  @override
  _i8.Future<double?> updateBeanWeightAfterBrew(
    String? beansUuid,
    double? usedAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightAfterBrew, [
              beansUuid,
              usedAmount,
            ]),
            returnValue: _i8.Future<double?>.value(),
            returnValueForMissingStub: _i8.Future<double?>.value(),
          )
          as _i8.Future<double?>);

  @override
  _i8.Future<double?> updateBeanWeightAfterBrewModification(
    String? beansUuid,
    double? coffeeAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightAfterBrewModification, [
              beansUuid,
              coffeeAmount,
            ]),
            returnValue: _i8.Future<double?>.value(),
            returnValueForMissingStub: _i8.Future<double?>.value(),
          )
          as _i8.Future<double?>);

  @override
  _i8.Future<double?> updateBeanWeightWhenBeansAdded(
    String? beansUuid,
    double? coffeeAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightWhenBeansAdded, [
              beansUuid,
              coffeeAmount,
            ]),
            returnValue: _i8.Future<double?>.value(),
            returnValueForMissingStub: _i8.Future<double?>.value(),
          )
          as _i8.Future<double?>);

  @override
  void printCacheStats() => super.noSuchMethod(
    Invocation.method(#printCacheStats, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i16.AnalyticsService {
  @override
  bool get brewsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#brewsEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get beansEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#beansEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get generalEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#generalEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get installId =>
      (super.noSuchMethod(
            Invocation.getter(#installId),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#installId),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#installId),
            ),
          )
          as String);

  @override
  int get bufferLength =>
      (super.noSuchMethod(
            Invocation.getter(#bufferLength),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<Map<String, dynamic>> get bufferedEventsForTesting =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedEventsForTesting),
            returnValue: <Map<String, dynamic>>[],
            returnValueForMissingStub: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void track(String? eventName, {Map<String, dynamic>? properties}) =>
      super.noSuchMethod(
        Invocation.method(#track, [eventName], {#properties: properties}),
        returnValueForMissingStub: null,
      );

  @override
  void setGlobalKillSwitch(bool? disabled) => super.noSuchMethod(
    Invocation.method(#setGlobalKillSwitch, [disabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setBrewsEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBrewsEnabled, [enabled]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setBeansEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBeansEnabled, [enabled]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setGeneralEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setGeneralEnabled, [enabled]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> flushNow() =>
      (super.noSuchMethod(
            Invocation.method(#flushNow, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
