// Mocks generated by Mockito 5.4.6 from annotations
// in coffee_timer/test/unit/widgets/settings_root_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i5;

import 'package:coffee_timer/database/database.dart' as _i2;
import 'package:coffee_timer/models/launch_popup_model.dart' as _i10;
import 'package:coffee_timer/models/recipe_model.dart' as _i7;
import 'package:coffee_timer/models/supported_locale_model.dart' as _i11;
import 'package:coffee_timer/providers/database_provider.dart' as _i3;
import 'package:coffee_timer/providers/recipe_provider.dart' as _i6;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseProvider_1 extends _i1.SmartFake
    implements _i3.DatabaseProvider {
  _FakeDatabaseProvider_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_3 extends _i1.SmartFake implements _i5.Locale {
  _FakeLocale_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecipeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeProvider extends _i1.Mock implements _i6.RecipeProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseProvider get databaseProvider =>
      (super.noSuchMethod(
            Invocation.getter(#databaseProvider),
            returnValue: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
            returnValueForMissingStub: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
          )
          as _i3.DatabaseProvider);

  @override
  List<_i7.RecipeModel> get recipes =>
      (super.noSuchMethod(
            Invocation.getter(#recipes),
            returnValue: <_i7.RecipeModel>[],
            returnValueForMissingStub: <_i7.RecipeModel>[],
          )
          as List<_i7.RecipeModel>);

  @override
  _i4.ValueNotifier<Set<String>> get shownBrewingMethodIds =>
      (super.noSuchMethod(
            Invocation.getter(#shownBrewingMethodIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#shownBrewingMethodIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#shownBrewingMethodIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  _i4.ValueNotifier<Set<String>> get hiddenBrewingMethodIds =>
      (super.noSuchMethod(
            Invocation.getter(#hiddenBrewingMethodIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#hiddenBrewingMethodIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#hiddenBrewingMethodIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  _i5.Locale get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _FakeLocale_3(this, Invocation.getter(#currentLocale)),
            returnValueForMissingStub: _FakeLocale_3(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as _i5.Locale);

  @override
  _i4.ValueNotifier<Set<String>> get favoriteRecipeIds =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteRecipeIds),
            returnValue: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#favoriteRecipeIds),
            ),
            returnValueForMissingStub: _FakeValueNotifier_2<Set<String>>(
              this,
              Invocation.getter(#favoriteRecipeIds),
            ),
          )
          as _i4.ValueNotifier<Set<String>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> ensureDataReady() =>
      (super.noSuchMethod(
            Invocation.method(#ensureDataReady, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setUserBrewingMethodPreference(
    String? methodId,
    bool? show,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setUserBrewingMethodPreference, [
              methodId,
              show,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> resetBrewingMethodPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#resetBrewingMethodPreferences, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> fetchAllRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllRecipes, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i7.RecipeModel>> fetchRecipesForBrewingMethod(
    String? brewingMethodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecipesForBrewingMethod, [brewingMethodId]),
            returnValue: _i8.Future<List<_i7.RecipeModel>>.value(
              <_i7.RecipeModel>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i7.RecipeModel>>.value(
              <_i7.RecipeModel>[],
            ),
          )
          as _i8.Future<List<_i7.RecipeModel>>);

  @override
  _i8.Future<String> getBrewingMethodName(String? brewingMethodId) =>
      (super.noSuchMethod(
            Invocation.method(#getBrewingMethodName, [brewingMethodId]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getBrewingMethodName, [brewingMethodId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getBrewingMethodName, [brewingMethodId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i7.RecipeModel?> getRecipeById(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [recipeId]),
            returnValue: _i8.Future<_i7.RecipeModel?>.value(),
            returnValueForMissingStub: _i8.Future<_i7.RecipeModel?>.value(),
          )
          as _i8.Future<_i7.RecipeModel?>);

  @override
  _i8.Future<void> toggleFavorite(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [recipeId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveCustomAmounts(
    String? recipeId,
    double? coffeeAmount,
    double? waterAmount, {
    String? customGrindSize,
    double? customWaterTemp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveCustomAmounts,
              [recipeId, coffeeAmount, waterAmount],
              {
                #customGrindSize: customGrindSize,
                #customWaterTemp: customWaterTemp,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveSliderPositions(
    String? recipeId, {
    int? sweetnessSliderPosition,
    int? strengthSliderPosition,
    int? coffeeChroniclerSliderPosition,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveSliderPositions,
              [recipeId],
              {
                #sweetnessSliderPosition: sweetnessSliderPosition,
                #strengthSliderPosition: strengthSliderPosition,
                #coffeeChroniclerSliderPosition: coffeeChroniclerSliderPosition,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i7.RecipeModel?> getLastUsedRecipe() =>
      (super.noSuchMethod(
            Invocation.method(#getLastUsedRecipe, []),
            returnValue: _i8.Future<_i7.RecipeModel?>.value(),
            returnValueForMissingStub: _i8.Future<_i7.RecipeModel?>.value(),
          )
          as _i8.Future<_i7.RecipeModel?>);

  @override
  _i8.Future<String> fetchBrewingMethodName(String? brewingMethodId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#fetchBrewingMethodName, [brewingMethodId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  List<_i7.RecipeModel> getFavoriteRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteRecipes, []),
            returnValue: <_i7.RecipeModel>[],
            returnValueForMissingStub: <_i7.RecipeModel>[],
          )
          as List<_i7.RecipeModel>);

  @override
  _i8.Future<List<_i7.RecipeModel>> fetchFavoriteRecipes(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFavoriteRecipes, [locale]),
            returnValue: _i8.Future<List<_i7.RecipeModel>>.value(
              <_i7.RecipeModel>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i7.RecipeModel>>.value(
              <_i7.RecipeModel>[],
            ),
          )
          as _i8.Future<List<_i7.RecipeModel>>);

  @override
  _i8.Future<List<_i7.RecipeModel>> fetchRecipesForVendor(String? vendorId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecipesForVendor, [vendorId]),
            returnValue: _i8.Future<List<_i7.RecipeModel>>.value(
              <_i7.RecipeModel>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i7.RecipeModel>>.value(
              <_i7.RecipeModel>[],
            ),
          )
          as _i8.Future<List<_i7.RecipeModel>>);

  @override
  _i8.Future<_i10.LaunchPopupModel?> fetchLatestLaunchPopup(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLatestLaunchPopup, [locale]),
            returnValue: _i8.Future<_i10.LaunchPopupModel?>.value(),
            returnValueForMissingStub:
                _i8.Future<_i10.LaunchPopupModel?>.value(),
          )
          as _i8.Future<_i10.LaunchPopupModel?>);

  @override
  _i8.Future<List<_i11.SupportedLocaleModel>> fetchAllSupportedLocales() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllSupportedLocales, []),
            returnValue: _i8.Future<List<_i11.SupportedLocaleModel>>.value(
              <_i11.SupportedLocaleModel>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i11.SupportedLocaleModel>>.value(
                  <_i11.SupportedLocaleModel>[],
                ),
          )
          as _i8.Future<List<_i11.SupportedLocaleModel>>);

  @override
  _i8.Future<String> getLocaleName(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#getLocaleName, [localeCode]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getLocaleName, [localeCode]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getLocaleName, [localeCode]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> setLocale(_i5.Locale? newLocale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [newLocale]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> getRandomCoffeeFactFromDB() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomCoffeeFactFromDB, []),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getRandomCoffeeFactFromDB, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getRandomCoffeeFactFromDB, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getLocalizedRecipeName(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalizedRecipeName, [recipeId]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getLocalizedRecipeName, [recipeId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getLocalizedRecipeName, [recipeId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<String>> fetchAllDistinctRoasters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoasters, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> fetchAllDistinctBeans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctBeans, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> searchRoasters(String? filter) =>
      (super.noSuchMethod(
            Invocation.method(#searchRoasters, [filter]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> searchBeans(String? filter) =>
      (super.noSuchMethod(
            Invocation.method(#searchBeans, [filter]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
