// Mocks generated by Mockito 5.4.6 from annotations
// in coffee_timer/test/unit/widgets/widget_async_context_batch_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:coffee_timer/controllers/coffee_beans_detail_controller.dart'
    as _i2;
import 'package:coffee_timer/database/database.dart' as _i9;
import 'package:coffee_timer/models/gift_offer_model.dart' as _i7;
import 'package:coffee_timer/models/help_models.dart' as _i8;
import 'package:coffee_timer/providers/database_provider.dart' as _i6;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CoffeeBeansDetailController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoffeeBeansDetailController extends _i1.Mock
    implements _i2.CoffeeBeansDetailController {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(
            Invocation.getter(#hasError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasData =>
      (super.noSuchMethod(
            Invocation.getter(#hasData),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasLogos =>
      (super.noSuchMethod(
            Invocation.getter(#hasLogos),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> initialize(_i4.BuildContext? context, String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [context, uuid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadBean(
    _i4.BuildContext? context,
    String? uuid, {
    bool? deferAncillary = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadBean,
              [context, uuid],
              {#deferAncillary: deferAncillary},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void loadAncillaryData(_i4.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#loadAncillaryData, [context]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> refreshData(_i4.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#refreshData, [context]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> toggleFavorite(_i4.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [context]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> navigateToEdit(_i4.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#navigateToEdit, [context]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearData() => super.noSuchMethod(
    Invocation.method(#clearData, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> setPackageWeightToZero(_i4.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#setPackageWeightToZero, [context]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> saveNotesAndGrindSize(
    _i4.BuildContext? context, {
    String? notes,
    String? grindSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveNotesAndGrindSize,
              [context],
              {#notes: notes, #grindSize: grindSize},
            ),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteBean(_i4.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBean, [context]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseProvider extends _i1.Mock implements _i6.DatabaseProvider {
  @override
  _i3.Future<void> initializeDatabase({
    required bool? isFirstLaunch,
    String? locale,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeDatabase, [], {
              #isFirstLaunch: isFirstLaunch,
              #locale: locale,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.GiftOffer>> fetchGiftBoxOffers({
    required _i5.Locale? locale,
    String? regionCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGiftBoxOffers, [], {
              #locale: locale,
              #regionCode: regionCode,
            }),
            returnValue: _i3.Future<List<_i7.GiftOffer>>.value(
              <_i7.GiftOffer>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i7.GiftOffer>>.value(
              <_i7.GiftOffer>[],
            ),
          )
          as _i3.Future<List<_i7.GiftOffer>>);

  @override
  _i3.Future<_i7.GiftOffer?> fetchGiftOfferById(
    String? id, {
    required _i5.Locale? locale,
    String? regionCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchGiftOfferById,
              [id],
              {#locale: locale, #regionCode: regionCode},
            ),
            returnValue: _i3.Future<_i7.GiftOffer?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.GiftOffer?>.value(),
          )
          as _i3.Future<_i7.GiftOffer?>);

  @override
  _i3.Future<_i7.GiftOffer?> fetchGiftOfferBySlug(
    String? slug, {
    required _i5.Locale? locale,
    String? regionCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchGiftOfferBySlug,
              [slug],
              {#locale: locale, #regionCode: regionCode},
            ),
            returnValue: _i3.Future<_i7.GiftOffer?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.GiftOffer?>.value(),
          )
          as _i3.Future<_i7.GiftOffer?>);

  @override
  _i3.Future<void> syncUserRecipes(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserRecipes, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> syncImportedRecipes(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncImportedRecipes, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.HelpCategoryModel>> getHelpCategories(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#getHelpCategories, [locale]),
            returnValue: _i3.Future<List<_i8.HelpCategoryModel>>.value(
              <_i8.HelpCategoryModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i8.HelpCategoryModel>>.value(
                  <_i8.HelpCategoryModel>[],
                ),
          )
          as _i3.Future<List<_i8.HelpCategoryModel>>);

  @override
  _i3.Future<List<_i8.HelpArticleModel>> getHelpArticles(
    String? categorySlug,
    String? locale,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getHelpArticles, [categorySlug, locale]),
            returnValue: _i3.Future<List<_i8.HelpArticleModel>>.value(
              <_i8.HelpArticleModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i8.HelpArticleModel>>.value(
                  <_i8.HelpArticleModel>[],
                ),
          )
          as _i3.Future<List<_i8.HelpArticleModel>>);

  @override
  _i3.Future<_i8.HelpArticleModel?> getHelpArticle(
    String? slug,
    String? locale,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getHelpArticle, [slug, locale]),
            returnValue: _i3.Future<_i8.HelpArticleModel?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i8.HelpArticleModel?>.value(),
          )
          as _i3.Future<_i8.HelpArticleModel?>);

  @override
  _i3.Future<void> refreshHelpContent() =>
      (super.noSuchMethod(
            Invocation.method(#refreshHelpContent, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<double> fetchGlobalBrewedCoffeeAmount(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGlobalBrewedCoffeeAmount, [start, end]),
            returnValue: _i3.Future<double>.value(0.0),
            returnValueForMissingStub: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<double> fetchGlobalBrewedCoffeeAmountAggregated(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGlobalBrewedCoffeeAmountAggregated, [
              start,
              end,
            ]),
            returnValue: _i3.Future<double>.value(0.0),
            returnValueForMissingStub: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<int> fetchGlobalBrewsCountAggregated(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGlobalBrewsCountAggregated, [start, end]),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<String>> fetchGlobalTopRecipes(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGlobalTopRecipes, [start, end]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i3.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> fetchGlobalTopRecipesAggregated(
    DateTime? start,
    DateTime? end, {
    int? topN = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchGlobalTopRecipesAggregated,
              [start, end],
              {#topN: topN},
            ),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i3.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<_i6.YearlyPercentileResult?> fetchUserYearlyPercentile(
    int? year, {
    double? liters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchUserYearlyPercentile,
              [year],
              {#liters: liters},
            ),
            returnValue: _i3.Future<_i6.YearlyPercentileResult?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i6.YearlyPercentileResult?>.value(),
          )
          as _i3.Future<_i6.YearlyPercentileResult?>);

  @override
  _i3.Future<List<String>> fetchCountriesForLocale(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCountriesForLocale, [locale]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i3.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> fetchTastingNotesForLocale(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTastingNotesForLocale, [locale]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i3.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> fetchProcessingMethodsForLocale(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProcessingMethodsForLocale, [locale]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i3.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> fetchRoasters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRoasters, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i3.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, String?>> fetchCachedRoasterLogoUrls(
    String? roasterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCachedRoasterLogoUrls, [roasterName]),
            returnValue: _i3.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i3.Future<Map<String, String?>>);

  @override
  _i3.Future<bool> uploadUserPreferencesToSupabase() =>
      (super.noSuchMethod(
            Invocation.method(#uploadUserPreferencesToSupabase, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> reconcileUserPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#reconcileUserPreferences, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserPreferenceInSupabase(
    String? recipeId, {
    bool? isFavorite,
    int? sweetnessSliderPosition,
    int? strengthSliderPosition,
    int? coffeeChroniclerSliderPosition,
    double? customCoffeeAmount,
    double? customWaterAmount,
    String? customGrindSize,
    double? customWaterTemp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserPreferenceInSupabase,
              [recipeId],
              {
                #isFavorite: isFavorite,
                #sweetnessSliderPosition: sweetnessSliderPosition,
                #strengthSliderPosition: strengthSliderPosition,
                #coffeeChroniclerSliderPosition: coffeeChroniclerSliderPosition,
                #customCoffeeAmount: customCoffeeAmount,
                #customWaterAmount: customWaterAmount,
                #customGrindSize: customGrindSize,
                #customWaterTemp: customWaterTemp,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getPublicUserRecipeMetadata(
    String? recipeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicUserRecipeMetadata, [recipeId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> fetchFullPublicUserRecipeData(
    String? recipeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFullPublicUserRecipeData, [recipeId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> fetchAndInsertUserPreferencesFromSupabase() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAndInsertUserPreferencesFromSupabase, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.Recipe>> getRecipesNeedingModeration() =>
      (super.noSuchMethod(
            Invocation.method(#getRecipesNeedingModeration, []),
            returnValue: _i3.Future<List<_i9.Recipe>>.value(<_i9.Recipe>[]),
            returnValueForMissingStub: _i3.Future<List<_i9.Recipe>>.value(
              <_i9.Recipe>[],
            ),
          )
          as _i3.Future<List<_i9.Recipe>>);

  @override
  _i3.Future<void> clearNeedsModerationReview(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#clearNeedsModerationReview, [recipeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> ensureUserProfileExists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#ensureUserProfileExists, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
