/// Flutter icons CoffeeTimerIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoffeeTimerIcons
///      fonts:
///       - asset: fonts/CoffeeTimerIcons.ttf
///
///
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class CoffeeTimerIcons {
  CoffeeTimerIcons._();

  static const _kFontFam = 'CoffeeTimerIcons';
  static const String? _kFontPkg = null;

  static const IconData globe =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_mug =
      IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark_github =
      IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
