// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8jFkf8BjVdykSswk0_sk6ItzgiUO9E-o',
    appId: '1:990890928826:web:83f37169e0f200484db083',
    messagingSenderId: '990890928826',
    projectId: 'timer-coffee',
    authDomain: 'timer-coffee.firebaseapp.com',
    storageBucket: 'timer-coffee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_2puWEbKwN6Nfkn43taOocR_pLneuQNM',
    appId: '1:990890928826:android:9954f7788df18fd24db083',
    messagingSenderId: '990890928826',
    projectId: 'timer-coffee',
    storageBucket: 'timer-coffee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwx4WDsFsUcfw3Bwnr6r5zWVo4FLeQ-WA',
    appId: '1:990890928826:ios:667eff23d98d5eaf4db083',
    messagingSenderId: '990890928826',
    projectId: 'timer-coffee',
    storageBucket: 'timer-coffee.firebasestorage.app',
    iosClientId: '990890928826-pp04ai3erpt5qumsfe6ca1pn35m0lsti.apps.googleusercontent.com',
    iosBundleId: 'timer.coffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwx4WDsFsUcfw3Bwnr6r5zWVo4FLeQ-WA',
    appId: '1:990890928826:ios:667eff23d98d5eaf4db083',
    messagingSenderId: '990890928826',
    projectId: 'timer-coffee',
    storageBucket: 'timer-coffee.firebasestorage.app',
    iosClientId: '990890928826-pp04ai3erpt5qumsfe6ca1pn35m0lsti.apps.googleusercontent.com',
    iosBundleId: 'timer.coffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8jFkf8BjVdykSswk0_sk6ItzgiUO9E-o',
    appId: '1:990890928826:web:7ca007e0d12f45924db083',
    messagingSenderId: '990890928826',
    projectId: 'timer-coffee',
    authDomain: 'timer-coffee.firebaseapp.com',
    storageBucket: 'timer-coffee.firebasestorage.app',
  );
}
