# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   #"iPhone 14 Pro",
   #"iPhone 14 Pro Max"
   #"iPhone 15 Pro Max"
   "iPhone SE (3rd generation)"
   #"iPad Pro (12.9-inch) (5th generation)"
#   "iPhone 8",
#   "iPhone 8 Plus",
#   "iPhone SE",
#   "iPhone X",
#   "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p",
#   "Apple Watch Series 6 - 44mm"
 ])

languages([
   #"en-US",
   #"de-DE",
   "ar-SA",
   #"es-ES",
   #"es-MX",
   #"fr-FR",
   #"ja",
   #"pl",
   #"pt-BR",
   #"pt-PT",
   #"ru",
   #"zh-Hans",
   #"id",
   "it",
   #"ro",
   #"tr",
   #"uk",
   #"nl-NL"
])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
#override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

localize_simulator(true)
headless(true)
#clear_previous_screenshots(true)
number_of_retries(2)