// Mocks generated by Mockito 5.4.6 from annotations
// in coffee_timer/test/unit/controllers/coffee_beans_detail_controller_async_context_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i14;

import 'package:auto_route/auto_route.dart' as _i8;
import 'package:auto_route/src/matcher/route_matcher.dart' as _i9;
import 'package:auto_route/src/router/controller/navigation_history/navigation_history_base.dart'
    as _i10;
import 'package:coffee_timer/database/database.dart' as _i2;
import 'package:coffee_timer/models/coffee_beans_model.dart' as _i13;
import 'package:coffee_timer/models/user_stat_model.dart' as _i16;
import 'package:coffee_timer/providers/coffee_beans_provider.dart' as _i4;
import 'package:coffee_timer/providers/database_provider.dart' as _i3;
import 'package:coffee_timer/providers/user_stat_provider.dart' as _i15;
import 'package:coffee_timer/services/feature_flags/feature_flags_repository.dart'
    as _i5;
import 'package:coffee_timer/services/roaster_logo_service.dart' as _i6;
import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseProvider_1 extends _i1.SmartFake
    implements _i3.DatabaseProvider {
  _FakeDatabaseProvider_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCoffeeBeansProvider_2 extends _i1.SmartFake
    implements _i4.CoffeeBeansProvider {
  _FakeCoffeeBeansProvider_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseFeatureFlagsDataSource_4 extends _i1.SmartFake
    implements _i5.SupabaseFeatureFlagsDataSource {
  _FakeSupabaseFeatureFlagsDataSource_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeLocalFeatureFlagsStore_5 extends _i1.SmartFake
    implements _i5.LocalFeatureFlagsStore {
  _FakeLocalFeatureFlagsStore_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoasterLogoResult_6 extends _i1.SmartFake
    implements _i6.RoasterLogoResult {
  _FakeRoasterLogoResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKey_7 extends _i1.SmartFake implements _i7.Key {
  _FakeKey_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePendingRoutesHandler_8 extends _i1.SmartFake
    implements _i8.PendingRoutesHandler {
  _FakePendingRoutesHandler_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePagelessRoutesObserver_9 extends _i1.SmartFake
    implements _i8.PagelessRoutesObserver {
  _FakePagelessRoutesObserver_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActiveGuardObserver_10 extends _i1.SmartFake
    implements _i8.ActiveGuardObserver {
  _FakeActiveGuardObserver_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_11<T extends _i7.State<_i7.StatefulWidget>>
    extends _i1.SmartFake
    implements _i7.GlobalKey<T> {
  _FakeGlobalKey_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteCollection_12 extends _i1.SmartFake
    implements _i8.RouteCollection {
  _FakeRouteCollection_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteMatcher_13 extends _i1.SmartFake implements _i9.RouteMatcher {
  _FakeRouteMatcher_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteData_14<R> extends _i1.SmartFake implements _i8.RouteData<R> {
  _FakeRouteData_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalObjectKey_15<T extends _i7.State<_i7.StatefulWidget>>
    extends _i1.SmartFake
    implements _i7.GlobalObjectKey<T> {
  _FakeGlobalObjectKey_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigationHistory_16 extends _i1.SmartFake
    implements _i10.NavigationHistory {
  _FakeNavigationHistory_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUrlState_17 extends _i1.SmartFake implements _i8.UrlState {
  _FakeUrlState_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRootStackRouter_18 extends _i1.SmartFake
    implements _i8.RootStackRouter {
  _FakeRootStackRouter_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteMatch_19<T> extends _i1.SmartFake implements _i8.RouteMatch<T> {
  _FakeRouteMatch_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutingController_20 extends _i1.SmartFake
    implements _i8.RoutingController {
  _FakeRoutingController_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CoffeeBeansProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoffeeBeansProvider extends _i1.Mock
    implements _i4.CoffeeBeansProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseProvider get databaseProvider =>
      (super.noSuchMethod(
            Invocation.getter(#databaseProvider),
            returnValue: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
            returnValueForMissingStub: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
          )
          as _i3.DatabaseProvider);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateCacheEntry(
    String? dataType,
    String? locale, {
    bool? isLocaleAgnostic = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #invalidateCacheEntry,
      [dataType, locale],
      {#isLocaleAgnostic: isLocaleAgnostic},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateDataType(String? dataType, {bool? isLocaleAgnostic = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #invalidateDataType,
          [dataType],
          {#isLocaleAgnostic: isLocaleAgnostic},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateExpiredEntries() => super.noSuchMethod(
    Invocation.method(#invalidateExpiredEntries, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> refreshDataType(
    String? dataType,
    String? locale, {
    bool? prefetch = false,
    bool? isLocaleAgnostic = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #refreshDataType,
              [dataType, locale],
              {#prefetch: prefetch, #isLocaleAgnostic: isLocaleAgnostic},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i13.CoffeeBeansModel>> fetchAllCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllCoffeeBeans, []),
            returnValue: _i12.Future<List<_i13.CoffeeBeansModel>>.value(
              <_i13.CoffeeBeansModel>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<_i13.CoffeeBeansModel>>.value(
                  <_i13.CoffeeBeansModel>[],
                ),
          )
          as _i12.Future<List<_i13.CoffeeBeansModel>>);

  @override
  _i12.Future<String> addCoffeeBeans(_i13.CoffeeBeansModel? beans) =>
      (super.noSuchMethod(
            Invocation.method(#addCoffeeBeans, [beans]),
            returnValue: _i12.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#addCoffeeBeans, [beans]),
              ),
            ),
            returnValueForMissingStub: _i12.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#addCoffeeBeans, [beans]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> updateCoffeeBeans(_i13.CoffeeBeansModel? beans) =>
      (super.noSuchMethod(
            Invocation.method(#updateCoffeeBeans, [beans]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteCoffeeBeans(String? beansUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCoffeeBeans, [beansUuid]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i13.CoffeeBeansModel?> fetchCoffeeBeansById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCoffeeBeansById, [id]),
            returnValue: _i12.Future<_i13.CoffeeBeansModel?>.value(),
            returnValueForMissingStub:
                _i12.Future<_i13.CoffeeBeansModel?>.value(),
          )
          as _i12.Future<_i13.CoffeeBeansModel?>);

  @override
  _i12.Future<_i13.CoffeeBeansModel?> fetchCoffeeBeansByUuid(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCoffeeBeansByUuid, [uuid]),
            returnValue: _i12.Future<_i13.CoffeeBeansModel?>.value(),
            returnValueForMissingStub:
                _i12.Future<_i13.CoffeeBeansModel?>.value(),
          )
          as _i12.Future<_i13.CoffeeBeansModel?>);

  @override
  _i12.Future<List<String>> fetchAllDistinctRoasters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoasters, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctNames() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctNames, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctVarieties() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctVarieties, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctProcessingMethods() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctProcessingMethods, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctRoastLevels() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoastLevels, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctOrigins() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctOrigins, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctTastingNotes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctTastingNotes, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctRegions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRegions, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctFarmers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctFarmers, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctFarms() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctFarms, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchAllDistinctGrindSizes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctGrindSizes, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchCombinedTastingNotes(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedTastingNotes, [locale]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchCombinedOrigins(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedOrigins, [locale]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchCombinedProcessingMethods(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedProcessingMethods, [locale]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<String>> fetchCombinedRoasters(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedRoasters, [locale]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<void> toggleFavoriteStatus(String? uuid, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteStatus, [uuid, isFavorite]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> backfillMissingUuids() =>
      (super.noSuchMethod(
            Invocation.method(#backfillMissingUuids, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> batchUploadCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#batchUploadCoffeeBeans, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> batchDownloadCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#batchDownloadCoffeeBeans, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#syncCoffeeBeans, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncNewCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#syncNewCoffeeBeans, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i13.CoffeeBeansModel>> fetchFilteredCoffeeBeans({
    List<String>? roasters,
    List<String>? origins,
    bool? isFavorite,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFilteredCoffeeBeans, [], {
              #roasters: roasters,
              #origins: origins,
              #isFavorite: isFavorite,
            }),
            returnValue: _i12.Future<List<_i13.CoffeeBeansModel>>.value(
              <_i13.CoffeeBeansModel>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<_i13.CoffeeBeansModel>>.value(
                  <_i13.CoffeeBeansModel>[],
                ),
          )
          as _i12.Future<List<_i13.CoffeeBeansModel>>);

  @override
  _i12.Future<List<String>> fetchOriginsForRoasters(
    List<String>? selectedRoasters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOriginsForRoasters, [selectedRoasters]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<double?> updateBeanWeightAfterBrew(
    String? beansUuid,
    double? usedAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightAfterBrew, [
              beansUuid,
              usedAmount,
            ]),
            returnValue: _i12.Future<double?>.value(),
            returnValueForMissingStub: _i12.Future<double?>.value(),
          )
          as _i12.Future<double?>);

  @override
  _i12.Future<double?> updateBeanWeightAfterBrewModification(
    String? beansUuid,
    double? coffeeAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightAfterBrewModification, [
              beansUuid,
              coffeeAmount,
            ]),
            returnValue: _i12.Future<double?>.value(),
            returnValueForMissingStub: _i12.Future<double?>.value(),
          )
          as _i12.Future<double?>);

  @override
  _i12.Future<double?> updateBeanWeightWhenBeansAdded(
    String? beansUuid,
    double? coffeeAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightWhenBeansAdded, [
              beansUuid,
              coffeeAmount,
            ]),
            returnValue: _i12.Future<double?>.value(),
            returnValueForMissingStub: _i12.Future<double?>.value(),
          )
          as _i12.Future<double?>);

  @override
  void printCacheStats() => super.noSuchMethod(
    Invocation.method(#printCacheStats, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserStatProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserStatProvider extends _i1.Mock implements _i15.UserStatProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i4.CoffeeBeansProvider get coffeeBeansProvider =>
      (super.noSuchMethod(
            Invocation.getter(#coffeeBeansProvider),
            returnValue: _FakeCoffeeBeansProvider_2(
              this,
              Invocation.getter(#coffeeBeansProvider),
            ),
            returnValueForMissingStub: _FakeCoffeeBeansProvider_2(
              this,
              Invocation.getter(#coffeeBeansProvider),
            ),
          )
          as _i4.CoffeeBeansProvider);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<void> insertUserStat({
    required String? recipeId,
    required double? coffeeAmount,
    required double? waterAmount,
    required int? sweetnessSliderPosition,
    required int? strengthSliderPosition,
    required String? brewingMethodId,
    String? notes,
    String? beans,
    String? roaster,
    double? rating,
    int? coffeeBeansId,
    bool? isMarked = false,
    String? coffeeBeansUuid,
    String? grindSize,
    String? statUuid,
    DateTime? createdAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserStat, [], {
              #recipeId: recipeId,
              #coffeeAmount: coffeeAmount,
              #waterAmount: waterAmount,
              #sweetnessSliderPosition: sweetnessSliderPosition,
              #strengthSliderPosition: strengthSliderPosition,
              #brewingMethodId: brewingMethodId,
              #notes: notes,
              #beans: beans,
              #roaster: roaster,
              #rating: rating,
              #coffeeBeansId: coffeeBeansId,
              #isMarked: isMarked,
              #coffeeBeansUuid: coffeeBeansUuid,
              #grindSize: grindSize,
              #statUuid: statUuid,
              #createdAt: createdAt,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateUserStat({
    required String? statUuid,
    String? recipeId,
    double? coffeeAmount,
    double? waterAmount,
    int? sweetnessSliderPosition,
    int? strengthSliderPosition,
    String? brewingMethodId,
    String? notes,
    String? beans,
    String? roaster,
    double? rating,
    int? coffeeBeansId,
    bool? isMarked,
    String? coffeeBeansUuid,
    String? grindSize,
    bool? clearBeans = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStat, [], {
              #statUuid: statUuid,
              #recipeId: recipeId,
              #coffeeAmount: coffeeAmount,
              #waterAmount: waterAmount,
              #sweetnessSliderPosition: sweetnessSliderPosition,
              #strengthSliderPosition: strengthSliderPosition,
              #brewingMethodId: brewingMethodId,
              #notes: notes,
              #beans: beans,
              #roaster: roaster,
              #rating: rating,
              #coffeeBeansId: coffeeBeansId,
              #isMarked: isMarked,
              #coffeeBeansUuid: coffeeBeansUuid,
              #grindSize: grindSize,
              #clearBeans: clearBeans,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteUserStat(String? statUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserStat, [statUuid]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i16.UserStatsModel>> fetchAllUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllUserStats, []),
            returnValue: _i12.Future<List<_i16.UserStatsModel>>.value(
              <_i16.UserStatsModel>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<_i16.UserStatsModel>>.value(
                  <_i16.UserStatsModel>[],
                ),
          )
          as _i12.Future<List<_i16.UserStatsModel>>);

  @override
  _i12.Future<_i16.UserStatsModel?> fetchUserStatByUuid(String? statUuid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserStatByUuid, [statUuid]),
            returnValue: _i12.Future<_i16.UserStatsModel?>.value(),
            returnValueForMissingStub:
                _i12.Future<_i16.UserStatsModel?>.value(),
          )
          as _i12.Future<_i16.UserStatsModel?>);

  @override
  _i12.Future<List<_i16.UserStatsModel>> fetchStatsByBeanUuid(
    String? beansUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStatsByBeanUuid, [beansUuid]),
            returnValue: _i12.Future<List<_i16.UserStatsModel>>.value(
              <_i16.UserStatsModel>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<_i16.UserStatsModel>>.value(
                  <_i16.UserStatsModel>[],
                ),
          )
          as _i12.Future<List<_i16.UserStatsModel>>);

  @override
  _i12.Future<int?> estimateBrewsLeft({
    required String? beansUuid,
    required double? packageWeightGrams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#estimateBrewsLeft, [], {
              #beansUuid: beansUuid,
              #packageWeightGrams: packageWeightGrams,
            }),
            returnValue: _i12.Future<int?>.value(),
            returnValueForMissingStub: _i12.Future<int?>.value(),
          )
          as _i12.Future<int?>);

  @override
  _i12.Future<_i16.UserStatsModel?> fetchUserStatById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserStatById, [id]),
            returnValue: _i12.Future<_i16.UserStatsModel?>.value(),
            returnValueForMissingStub:
                _i12.Future<_i16.UserStatsModel?>.value(),
          )
          as _i12.Future<_i16.UserStatsModel?>);

  @override
  _i12.Future<void> batchUploadUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#batchUploadUserStats, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> batchDownloadUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#batchDownloadUserStats, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#syncUserStats, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteUserStatById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserStatById, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<double> fetchBrewedCoffeeAmountForPeriod(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBrewedCoffeeAmountForPeriod, [start, end]),
            returnValue: _i12.Future<double>.value(0.0),
            returnValueForMissingStub: _i12.Future<double>.value(0.0),
          )
          as _i12.Future<double>);

  @override
  _i12.Future<List<String>> fetchTopRecipeIdsForPeriod(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRecipeIdsForPeriod, [start, end]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  DateTime getStartOfToday() =>
      (super.noSuchMethod(
            Invocation.method(#getStartOfToday, []),
            returnValue: _FakeDateTime_3(
              this,
              Invocation.method(#getStartOfToday, []),
            ),
            returnValueForMissingStub: _FakeDateTime_3(
              this,
              Invocation.method(#getStartOfToday, []),
            ),
          )
          as DateTime);

  @override
  DateTime getEndOfToday() =>
      (super.noSuchMethod(
            Invocation.method(#getEndOfToday, []),
            returnValue: _FakeDateTime_3(
              this,
              Invocation.method(#getEndOfToday, []),
            ),
            returnValueForMissingStub: _FakeDateTime_3(
              this,
              Invocation.method(#getEndOfToday, []),
            ),
          )
          as DateTime);

  @override
  DateTime getStartOfWeek() =>
      (super.noSuchMethod(
            Invocation.method(#getStartOfWeek, []),
            returnValue: _FakeDateTime_3(
              this,
              Invocation.method(#getStartOfWeek, []),
            ),
            returnValueForMissingStub: _FakeDateTime_3(
              this,
              Invocation.method(#getStartOfWeek, []),
            ),
          )
          as DateTime);

  @override
  DateTime getStartOfMonth() =>
      (super.noSuchMethod(
            Invocation.method(#getStartOfMonth, []),
            returnValue: _FakeDateTime_3(
              this,
              Invocation.method(#getStartOfMonth, []),
            ),
            returnValueForMissingStub: _FakeDateTime_3(
              this,
              Invocation.method(#getStartOfMonth, []),
            ),
          )
          as DateTime);

  @override
  _i12.Future<void> backfillMissingCoffeeBeansUuids() =>
      (super.noSuchMethod(
            Invocation.method(#backfillMissingCoffeeBeansUuids, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> backfillMissingStatUuids() =>
      (super.noSuchMethod(
            Invocation.method(#backfillMissingStatUuids, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncNewUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#syncNewUserStats, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FeatureFlagsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeatureFlagsRepository extends _i1.Mock
    implements _i5.FeatureFlagsRepository {
  @override
  _i5.SupabaseFeatureFlagsDataSource get remote =>
      (super.noSuchMethod(
            Invocation.getter(#remote),
            returnValue: _FakeSupabaseFeatureFlagsDataSource_4(
              this,
              Invocation.getter(#remote),
            ),
            returnValueForMissingStub: _FakeSupabaseFeatureFlagsDataSource_4(
              this,
              Invocation.getter(#remote),
            ),
          )
          as _i5.SupabaseFeatureFlagsDataSource);

  @override
  _i5.LocalFeatureFlagsStore get local =>
      (super.noSuchMethod(
            Invocation.getter(#local),
            returnValue: _FakeLocalFeatureFlagsStore_5(
              this,
              Invocation.getter(#local),
            ),
            returnValueForMissingStub: _FakeLocalFeatureFlagsStore_5(
              this,
              Invocation.getter(#local),
            ),
          )
          as _i5.LocalFeatureFlagsStore);

  @override
  String get platform =>
      (super.noSuchMethod(
            Invocation.getter(#platform),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#platform),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#platform),
            ),
          )
          as String);

  @override
  int get buildNumber =>
      (super.noSuchMethod(
            Invocation.getter(#buildNumber),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  Map<String, bool> get currentFlags =>
      (super.noSuchMethod(
            Invocation.getter(#currentFlags),
            returnValue: <String, bool>{},
            returnValueForMissingStub: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i12.Stream<Map<String, bool>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<Map<String, bool>>.empty(),
            returnValueForMissingStub: _i12.Stream<Map<String, bool>>.empty(),
          )
          as _i12.Stream<Map<String, bool>>);

  @override
  bool isEnabled(String? key, {bool? defaultValue = false}) =>
      (super.noSuchMethod(
            Invocation.method(#isEnabled, [key], {#defaultValue: defaultValue}),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RoasterLogoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoasterLogoService extends _i1.Mock
    implements _i6.RoasterLogoService {
  @override
  _i12.Future<_i6.RoasterLogoResult> fetchRoasterLogos(
    _i7.BuildContext? context,
    String? roasterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRoasterLogos, [context, roasterName]),
            returnValue: _i12.Future<_i6.RoasterLogoResult>.value(
              _FakeRoasterLogoResult_6(
                this,
                Invocation.method(#fetchRoasterLogos, [context, roasterName]),
              ),
            ),
            returnValueForMissingStub: _i12.Future<_i6.RoasterLogoResult>.value(
              _FakeRoasterLogoResult_6(
                this,
                Invocation.method(#fetchRoasterLogos, [context, roasterName]),
              ),
            ),
          )
          as _i12.Future<_i6.RoasterLogoResult>);

  @override
  _i12.Future<bool> hasLogosAvailable(
    _i7.BuildContext? context,
    String? roasterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasLogosAvailable, [context, roasterName]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<Map<String, _i6.RoasterLogoResult>> fetchMultipleRoasterLogos(
    _i7.BuildContext? context,
    List<String>? roasterNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMultipleRoasterLogos, [
              context,
              roasterNames,
            ]),
            returnValue: _i12.Future<Map<String, _i6.RoasterLogoResult>>.value(
              <String, _i6.RoasterLogoResult>{},
            ),
            returnValueForMissingStub:
                _i12.Future<Map<String, _i6.RoasterLogoResult>>.value(
                  <String, _i6.RoasterLogoResult>{},
                ),
          )
          as _i12.Future<Map<String, _i6.RoasterLogoResult>>);
}

/// A class which mocks [StackRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRouter extends _i1.Mock implements _i8.StackRouter {
  @override
  _i7.Key get key =>
      (super.noSuchMethod(
            Invocation.getter(#key),
            returnValue: _FakeKey_7(this, Invocation.getter(#key)),
            returnValueForMissingStub: _FakeKey_7(
              this,
              Invocation.getter(#key),
            ),
          )
          as _i7.Key);

  @override
  _i7.Key get matchId =>
      (super.noSuchMethod(
            Invocation.getter(#matchId),
            returnValue: _FakeKey_7(this, Invocation.getter(#matchId)),
            returnValueForMissingStub: _FakeKey_7(
              this,
              Invocation.getter(#matchId),
            ),
          )
          as _i7.Key);

  @override
  _i8.PendingRoutesHandler get pendingRoutesHandler =>
      (super.noSuchMethod(
            Invocation.getter(#pendingRoutesHandler),
            returnValue: _FakePendingRoutesHandler_8(
              this,
              Invocation.getter(#pendingRoutesHandler),
            ),
            returnValueForMissingStub: _FakePendingRoutesHandler_8(
              this,
              Invocation.getter(#pendingRoutesHandler),
            ),
          )
          as _i8.PendingRoutesHandler);

  @override
  int get stateHash =>
      (super.noSuchMethod(
            Invocation.getter(#stateHash),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i8.PagelessRoutesObserver get pagelessRoutesObserver =>
      (super.noSuchMethod(
            Invocation.getter(#pagelessRoutesObserver),
            returnValue: _FakePagelessRoutesObserver_9(
              this,
              Invocation.getter(#pagelessRoutesObserver),
            ),
            returnValueForMissingStub: _FakePagelessRoutesObserver_9(
              this,
              Invocation.getter(#pagelessRoutesObserver),
            ),
          )
          as _i8.PagelessRoutesObserver);

  @override
  _i8.ActiveGuardObserver get activeGuardObserver =>
      (super.noSuchMethod(
            Invocation.getter(#activeGuardObserver),
            returnValue: _FakeActiveGuardObserver_10(
              this,
              Invocation.getter(#activeGuardObserver),
            ),
            returnValueForMissingStub: _FakeActiveGuardObserver_10(
              this,
              Invocation.getter(#activeGuardObserver),
            ),
          )
          as _i8.ActiveGuardObserver);

  @override
  _i7.GlobalKey<_i7.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_11<_i7.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_11<_i7.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i7.GlobalKey<_i7.NavigatorState>);

  @override
  _i8.RouteCollection get routeCollection =>
      (super.noSuchMethod(
            Invocation.getter(#routeCollection),
            returnValue: _FakeRouteCollection_12(
              this,
              Invocation.getter(#routeCollection),
            ),
            returnValueForMissingStub: _FakeRouteCollection_12(
              this,
              Invocation.getter(#routeCollection),
            ),
          )
          as _i8.RouteCollection);

  @override
  _i9.RouteMatcher get matcher =>
      (super.noSuchMethod(
            Invocation.getter(#matcher),
            returnValue: _FakeRouteMatcher_13(
              this,
              Invocation.getter(#matcher),
            ),
            returnValueForMissingStub: _FakeRouteMatcher_13(
              this,
              Invocation.getter(#matcher),
            ),
          )
          as _i9.RouteMatcher);

  @override
  _i8.RouteData<dynamic> get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeRouteData_14<dynamic>(
              this,
              Invocation.getter(#current),
            ),
            returnValueForMissingStub: _FakeRouteData_14<dynamic>(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i8.RouteData<dynamic>);

  @override
  _i8.RouteData<dynamic> get topRoute =>
      (super.noSuchMethod(
            Invocation.getter(#topRoute),
            returnValue: _FakeRouteData_14<dynamic>(
              this,
              Invocation.getter(#topRoute),
            ),
            returnValueForMissingStub: _FakeRouteData_14<dynamic>(
              this,
              Invocation.getter(#topRoute),
            ),
          )
          as _i8.RouteData<dynamic>);

  @override
  bool get hasPagelessTopRoute =>
      (super.noSuchMethod(
            Invocation.getter(#hasPagelessTopRoute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i8.AutoRoutePage<dynamic>> get stack =>
      (super.noSuchMethod(
            Invocation.getter(#stack),
            returnValue: <_i8.AutoRoutePage<dynamic>>[],
            returnValueForMissingStub: <_i8.AutoRoutePage<dynamic>>[],
          )
          as List<_i8.AutoRoutePage<dynamic>>);

  @override
  bool get ignorePopCompleters =>
      (super.noSuchMethod(
            Invocation.getter(#ignorePopCompleters),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.GlobalObjectKey<_i7.State<_i7.StatefulWidget>> get globalRouterKey =>
      (super.noSuchMethod(
            Invocation.getter(#globalRouterKey),
            returnValue: _FakeGlobalObjectKey_15<_i7.State<_i7.StatefulWidget>>(
              this,
              Invocation.getter(#globalRouterKey),
            ),
            returnValueForMissingStub:
                _FakeGlobalObjectKey_15<_i7.State<_i7.StatefulWidget>>(
                  this,
                  Invocation.getter(#globalRouterKey),
                ),
          )
          as _i7.GlobalObjectKey<_i7.State<_i7.StatefulWidget>>);

  @override
  List<_i8.RoutingController> get childControllers =>
      (super.noSuchMethod(
            Invocation.getter(#childControllers),
            returnValue: <_i8.RoutingController>[],
            returnValueForMissingStub: <_i8.RoutingController>[],
          )
          as List<_i8.RoutingController>);

  @override
  _i10.NavigationHistory get navigationHistory =>
      (super.noSuchMethod(
            Invocation.getter(#navigationHistory),
            returnValue: _FakeNavigationHistory_16(
              this,
              Invocation.getter(#navigationHistory),
            ),
            returnValueForMissingStub: _FakeNavigationHistory_16(
              this,
              Invocation.getter(#navigationHistory),
            ),
          )
          as _i10.NavigationHistory);

  @override
  _i8.UrlState get urlState =>
      (super.noSuchMethod(
            Invocation.getter(#urlState),
            returnValue: _FakeUrlState_17(this, Invocation.getter(#urlState)),
            returnValueForMissingStub: _FakeUrlState_17(
              this,
              Invocation.getter(#urlState),
            ),
          )
          as _i8.UrlState);

  @override
  String get currentPath =>
      (super.noSuchMethod(
            Invocation.getter(#currentPath),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#currentPath),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#currentPath),
            ),
          )
          as String);

  @override
  String get currentUrl =>
      (super.noSuchMethod(
            Invocation.getter(#currentUrl),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#currentUrl),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#currentUrl),
            ),
          )
          as String);

  @override
  List<_i8.RouteData<dynamic>> get stackData =>
      (super.noSuchMethod(
            Invocation.getter(#stackData),
            returnValue: <_i8.RouteData<dynamic>>[],
            returnValueForMissingStub: <_i8.RouteData<dynamic>>[],
          )
          as List<_i8.RouteData<dynamic>>);

  @override
  bool get managedByWidget =>
      (super.noSuchMethod(
            Invocation.getter(#managedByWidget),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isTopMost =>
      (super.noSuchMethod(
            Invocation.getter(#isTopMost),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canNavigateBack =>
      (super.noSuchMethod(
            Invocation.getter(#canNavigateBack),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.RootStackRouter get root =>
      (super.noSuchMethod(
            Invocation.getter(#root),
            returnValue: _FakeRootStackRouter_18(
              this,
              Invocation.getter(#root),
            ),
            returnValueForMissingStub: _FakeRootStackRouter_18(
              this,
              Invocation.getter(#root),
            ),
          )
          as _i8.RootStackRouter);

  @override
  bool get isRoot =>
      (super.noSuchMethod(
            Invocation.getter(#isRoot),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.RouteMatch<dynamic> get topMatch =>
      (super.noSuchMethod(
            Invocation.getter(#topMatch),
            returnValue: _FakeRouteMatch_19<dynamic>(
              this,
              Invocation.getter(#topMatch),
            ),
            returnValueForMissingStub: _FakeRouteMatch_19<dynamic>(
              this,
              Invocation.getter(#topMatch),
            ),
          )
          as _i8.RouteMatch<dynamic>);

  @override
  _i8.RouteData<dynamic> get routeData =>
      (super.noSuchMethod(
            Invocation.getter(#routeData),
            returnValue: _FakeRouteData_14<dynamic>(
              this,
              Invocation.getter(#routeData),
            ),
            returnValueForMissingStub: _FakeRouteData_14<dynamic>(
              this,
              Invocation.getter(#routeData),
            ),
          )
          as _i8.RouteData<dynamic>);

  @override
  bool get hasEntries =>
      (super.noSuchMethod(
            Invocation.getter(#hasEntries),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get pageCount =>
      (super.noSuchMethod(
            Invocation.getter(#pageCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i8.RouteMatch<dynamic>> get currentSegments =>
      (super.noSuchMethod(
            Invocation.getter(#currentSegments),
            returnValue: <_i8.RouteMatch<dynamic>>[],
            returnValueForMissingStub: <_i8.RouteMatch<dynamic>>[],
          )
          as List<_i8.RouteMatch<dynamic>>);

  @override
  set ignorePopCompleters(bool? value) => super.noSuchMethod(
    Invocation.setter(#ignorePopCompleters, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> reevaluateGuards() =>
      (super.noSuchMethod(
            Invocation.method(#reevaluateGuards, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  bool canPop({
    bool? ignoreChildRoutes = false,
    bool? ignoreParentRoutes = false,
    bool? ignorePagelessRoutes = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#canPop, [], {
              #ignoreChildRoutes: ignoreChildRoutes,
              #ignoreParentRoutes: ignoreParentRoutes,
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<T?> pushWidget<T extends Object?>(
    _i7.Widget? widget, {
    _i7.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
    bool? opaque = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushWidget,
              [widget],
              {
                #transitionBuilder: transitionBuilder,
                #fullscreenDialog: fullscreenDialog,
                #transitionDuration: transitionDuration,
                #opaque: opaque,
              },
            ),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  _i12.Future<T?> pushNativeRoute<T extends Object?>(_i7.Route<T>? route) =>
      (super.noSuchMethod(
            Invocation.method(#pushNativeRoute, [route]),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  _i12.Future<bool> maybePop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#maybePop, [result]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#popForced, [result]),
    returnValueForMissingStub: null,
  );

  @override
  bool removeLast() =>
      (super.noSuchMethod(
            Invocation.method(#removeLast, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void removeRoute(_i8.RouteData<dynamic>? route, {bool? notify = true}) =>
      super.noSuchMethod(
        Invocation.method(#removeRoute, [route], {#notify: notify}),
        returnValueForMissingStub: null,
      );

  @override
  void onPopPage(_i8.AutoRoutePage<Object?>? page) => super.noSuchMethod(
    Invocation.method(#onPopPage, [page]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<T?> push<T extends Object?>(
    _i8.PageRouteInfo<Object?>? route, {
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#push, [route], {#onFailure: onFailure}),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  _i12.Future<void> insert(
    _i8.PageRouteInfo<Object?>? route, {
    int? index = 0,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [route],
              {#index: index, #onFailure: onFailure},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<T?> replace<T extends Object?>(
    _i8.PageRouteInfo<Object?>? route, {
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [route], {#onFailure: onFailure}),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  _i12.Future<void> pushAll(
    List<_i8.PageRouteInfo<Object?>>? routes, {
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushAll, [routes], {#onFailure: onFailure}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> popAndPushAll(
    List<_i8.PageRouteInfo<Object?>>? routes, {
    dynamic onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #popAndPushAll,
              [routes],
              {#onFailure: onFailure},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> replaceAll(
    List<_i8.PageRouteInfo<Object?>>? routes, {
    _i8.OnNavigationFailure? onFailure,
    bool? updateExistingRoutes = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceAll,
              [routes],
              {
                #onFailure: onFailure,
                #updateExistingRoutes: updateExistingRoutes,
              },
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void popUntilRoot() => super.noSuchMethod(
    Invocation.method(#popUntilRoot, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<T?> popAndPush<T extends Object?, TO extends Object?>(
    _i8.PageRouteInfo<Object?>? route, {
    TO? result,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #popAndPush,
              [route],
              {#result: result, #onFailure: onFailure},
            ),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  bool removeUntil(_i8.RouteDataPredicate? predicate, {bool? scoped = true}) =>
      (super.noSuchMethod(
            Invocation.method(#removeUntil, [predicate], {#scoped: scoped}),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void popUntil(_i7.RoutePredicate? predicate, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntil, [predicate], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  bool removeWhere(_i8.RouteDataPredicate? predicate, {bool? notify = true}) =>
      (super.noSuchMethod(
            Invocation.method(#removeWhere, [predicate], {#notify: notify}),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void updateDeclarativeRoutes(List<_i8.PageRouteInfo<Object?>>? routes) =>
      super.noSuchMethod(
        Invocation.method(#updateDeclarativeRoutes, [routes]),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> navigateAll(
    List<_i8.RouteMatch<dynamic>>? routes, {
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigateAll, [routes], {#onFailure: onFailure}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<T?> pushAndPopUntil<T extends Object?>(
    _i8.PageRouteInfo<Object?>? route, {
    required _i7.RoutePredicate? predicate,
    bool? scopedPopUntil = true,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushAndPopUntil,
              [route],
              {
                #predicate: predicate,
                #scopedPopUntil: scopedPopUntil,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  _i12.Future<T?> replacePath<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replacePath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  _i12.Future<T?> replaceNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  _i12.Future<T?> pushPath<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushPath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  _i12.Future<T?> pushNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i12.Future<T?>.value(),
            returnValueForMissingStub: _i12.Future<T?>.value(),
          )
          as _i12.Future<T?>);

  @override
  void popUntilRouteWithName(String? name, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntilRouteWithName, [name], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  void popUntilRouteWithPath(String? path, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntilRouteWithPath, [path], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  void markUrlStateForReplace() => super.noSuchMethod(
    Invocation.method(#markUrlStateForReplace, []),
    returnValueForMissingStub: null,
  );

  @override
  void attachChildController(_i8.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(#attachChildController, [childController]),
        returnValueForMissingStub: null,
      );

  @override
  void removeChildController(_i8.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(#removeChildController, [childController]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAll({bool? forceUrlRebuild = false}) => super.noSuchMethod(
    Invocation.method(#notifyAll, [], {#forceUrlRebuild: forceUrlRebuild}),
    returnValueForMissingStub: null,
  );

  @override
  List<_i8.HierarchySegment> currentHierarchy({
    bool? asPath = false,
    bool? ignorePending = false,
    bool? ignoreParams = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#currentHierarchy, [], {
              #asPath: asPath,
              #ignorePending: ignorePending,
              #ignoreParams: ignoreParams,
            }),
            returnValue: <_i8.HierarchySegment>[],
            returnValueForMissingStub: <_i8.HierarchySegment>[],
          )
          as List<_i8.HierarchySegment>);

  @override
  bool isRouteActive(String? routeName) =>
      (super.noSuchMethod(
            Invocation.method(#isRouteActive, [routeName]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isRouteDataActive(_i8.RouteData<dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#isRouteDataActive, [data]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isPathActive(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#isPathActive, [path]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.RouteMatch<dynamic>? match(_i8.PageRouteInfo<Object?>? route) =>
      (super.noSuchMethod(
            Invocation.method(#match, [route]),
            returnValueForMissingStub: null,
          )
          as _i8.RouteMatch<dynamic>?);

  @override
  _i12.Future<dynamic> navigate(
    _i8.PageRouteInfo<Object?>? route, {
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigate, [route], {#onFailure: onFailure}),
            returnValue: _i12.Future<dynamic>.value(),
            returnValueForMissingStub: _i12.Future<dynamic>.value(),
          )
          as _i12.Future<dynamic>);

  @override
  _i12.Future<void> navigatePath(
    String? path, {
    bool? includePrefixMatches = false,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigatePath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> navigateNamed(
    String? path, {
    bool? includePrefixMatches = false,
    _i8.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void back() => super.noSuchMethod(
    Invocation.method(#back, []),
    returnValueForMissingStub: null,
  );

  @override
  void pushPathState(Object? state) => super.noSuchMethod(
    Invocation.method(#pushPathState, [state]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#topMostRouter, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: _FakeRoutingController_20(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
            returnValueForMissingStub: _FakeRoutingController_20(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
          )
          as _i8.RoutingController);

  @override
  void updateRouteData(_i8.RouteData<dynamic>? data) => super.noSuchMethod(
    Invocation.method(#updateRouteData, [data]),
    returnValueForMissingStub: null,
  );

  @override
  T? innerRouterOf<T extends _i8.RoutingController>(String? routeName) =>
      (super.noSuchMethod(
            Invocation.method(#innerRouterOf, [routeName]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  _i12.Future<bool> maybePopTop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#maybePopTop, [result]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  void popTop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#popTop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  bool childrenCanPop({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#childrenCanPop, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool activeRouterCanPop({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#activeRouterCanPop, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.PageRouteInfo<Object?>? buildPageRoute(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildPageRoute,
              [path],
              {#includePrefixMatches: includePrefixMatches},
            ),
            returnValueForMissingStub: null,
          )
          as _i8.PageRouteInfo<Object?>?);

  @override
  List<_i8.PageRouteInfo<Object?>>? buildPageRoutesStack(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildPageRoutesStack,
              [path],
              {#includePrefixMatches: includePrefixMatches},
            ),
            returnValueForMissingStub: null,
          )
          as List<_i8.PageRouteInfo<Object?>>?);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
