// Mocks generated by Mockito 5.4.6 from annotations
// in coffee_timer/test/unit/controllers/coffee_beans_controller_async_context_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i12;

import 'package:auto_route/auto_route.dart' as _i5;
import 'package:auto_route/src/matcher/route_matcher.dart' as _i6;
import 'package:auto_route/src/router/controller/navigation_history/navigation_history_base.dart'
    as _i7;
import 'package:coffee_timer/database/database.dart' as _i2;
import 'package:coffee_timer/models/coffee_beans_model.dart' as _i11;
import 'package:coffee_timer/providers/coffee_beans_provider.dart' as _i8;
import 'package:coffee_timer/providers/database_provider.dart' as _i3;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseProvider_1 extends _i1.SmartFake
    implements _i3.DatabaseProvider {
  _FakeDatabaseProvider_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKey_2 extends _i1.SmartFake implements _i4.Key {
  _FakeKey_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePendingRoutesHandler_3 extends _i1.SmartFake
    implements _i5.PendingRoutesHandler {
  _FakePendingRoutesHandler_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePagelessRoutesObserver_4 extends _i1.SmartFake
    implements _i5.PagelessRoutesObserver {
  _FakePagelessRoutesObserver_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActiveGuardObserver_5 extends _i1.SmartFake
    implements _i5.ActiveGuardObserver {
  _FakeActiveGuardObserver_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_6<T extends _i4.State<_i4.StatefulWidget>>
    extends _i1.SmartFake
    implements _i4.GlobalKey<T> {
  _FakeGlobalKey_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteCollection_7 extends _i1.SmartFake
    implements _i5.RouteCollection {
  _FakeRouteCollection_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteMatcher_8 extends _i1.SmartFake implements _i6.RouteMatcher {
  _FakeRouteMatcher_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteData_9<R> extends _i1.SmartFake implements _i5.RouteData<R> {
  _FakeRouteData_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalObjectKey_10<T extends _i4.State<_i4.StatefulWidget>>
    extends _i1.SmartFake
    implements _i4.GlobalObjectKey<T> {
  _FakeGlobalObjectKey_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigationHistory_11 extends _i1.SmartFake
    implements _i7.NavigationHistory {
  _FakeNavigationHistory_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUrlState_12 extends _i1.SmartFake implements _i5.UrlState {
  _FakeUrlState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRootStackRouter_13 extends _i1.SmartFake
    implements _i5.RootStackRouter {
  _FakeRootStackRouter_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteMatch_14<T> extends _i1.SmartFake implements _i5.RouteMatch<T> {
  _FakeRouteMatch_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutingController_15 extends _i1.SmartFake
    implements _i5.RoutingController {
  _FakeRoutingController_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CoffeeBeansProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoffeeBeansProvider extends _i1.Mock
    implements _i8.CoffeeBeansProvider {
  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseProvider get databaseProvider =>
      (super.noSuchMethod(
            Invocation.getter(#databaseProvider),
            returnValue: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
            returnValueForMissingStub: _FakeDatabaseProvider_1(
              this,
              Invocation.getter(#databaseProvider),
            ),
          )
          as _i3.DatabaseProvider);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateCacheEntry(
    String? dataType,
    String? locale, {
    bool? isLocaleAgnostic = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #invalidateCacheEntry,
      [dataType, locale],
      {#isLocaleAgnostic: isLocaleAgnostic},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateDataType(String? dataType, {bool? isLocaleAgnostic = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #invalidateDataType,
          [dataType],
          {#isLocaleAgnostic: isLocaleAgnostic},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateExpiredEntries() => super.noSuchMethod(
    Invocation.method(#invalidateExpiredEntries, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> refreshDataType(
    String? dataType,
    String? locale, {
    bool? prefetch = false,
    bool? isLocaleAgnostic = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #refreshDataType,
              [dataType, locale],
              {#prefetch: prefetch, #isLocaleAgnostic: isLocaleAgnostic},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i11.CoffeeBeansModel>> fetchAllCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllCoffeeBeans, []),
            returnValue: _i10.Future<List<_i11.CoffeeBeansModel>>.value(
              <_i11.CoffeeBeansModel>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i11.CoffeeBeansModel>>.value(
                  <_i11.CoffeeBeansModel>[],
                ),
          )
          as _i10.Future<List<_i11.CoffeeBeansModel>>);

  @override
  _i10.Future<String> addCoffeeBeans(_i11.CoffeeBeansModel? beans) =>
      (super.noSuchMethod(
            Invocation.method(#addCoffeeBeans, [beans]),
            returnValue: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#addCoffeeBeans, [beans]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#addCoffeeBeans, [beans]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> updateCoffeeBeans(_i11.CoffeeBeansModel? beans) =>
      (super.noSuchMethod(
            Invocation.method(#updateCoffeeBeans, [beans]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteCoffeeBeans(String? beansUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCoffeeBeans, [beansUuid]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i11.CoffeeBeansModel?> fetchCoffeeBeansById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCoffeeBeansById, [id]),
            returnValue: _i10.Future<_i11.CoffeeBeansModel?>.value(),
            returnValueForMissingStub:
                _i10.Future<_i11.CoffeeBeansModel?>.value(),
          )
          as _i10.Future<_i11.CoffeeBeansModel?>);

  @override
  _i10.Future<_i11.CoffeeBeansModel?> fetchCoffeeBeansByUuid(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCoffeeBeansByUuid, [uuid]),
            returnValue: _i10.Future<_i11.CoffeeBeansModel?>.value(),
            returnValueForMissingStub:
                _i10.Future<_i11.CoffeeBeansModel?>.value(),
          )
          as _i10.Future<_i11.CoffeeBeansModel?>);

  @override
  _i10.Future<List<String>> fetchAllDistinctRoasters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoasters, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctNames() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctNames, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctVarieties() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctVarieties, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctProcessingMethods() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctProcessingMethods, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctRoastLevels() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRoastLevels, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctOrigins() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctOrigins, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctTastingNotes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctTastingNotes, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctRegions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctRegions, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctFarmers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctFarmers, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctFarms() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctFarms, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchAllDistinctGrindSizes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDistinctGrindSizes, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchCombinedTastingNotes(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedTastingNotes, [locale]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchCombinedOrigins(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedOrigins, [locale]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchCombinedProcessingMethods(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedProcessingMethods, [locale]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<String>> fetchCombinedRoasters(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedRoasters, [locale]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<void> toggleFavoriteStatus(String? uuid, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteStatus, [uuid, isFavorite]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> backfillMissingUuids() =>
      (super.noSuchMethod(
            Invocation.method(#backfillMissingUuids, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> batchUploadCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#batchUploadCoffeeBeans, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> batchDownloadCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#batchDownloadCoffeeBeans, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> syncCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#syncCoffeeBeans, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> syncNewCoffeeBeans() =>
      (super.noSuchMethod(
            Invocation.method(#syncNewCoffeeBeans, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i11.CoffeeBeansModel>> fetchFilteredCoffeeBeans({
    List<String>? roasters,
    List<String>? origins,
    bool? isFavorite,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFilteredCoffeeBeans, [], {
              #roasters: roasters,
              #origins: origins,
              #isFavorite: isFavorite,
            }),
            returnValue: _i10.Future<List<_i11.CoffeeBeansModel>>.value(
              <_i11.CoffeeBeansModel>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i11.CoffeeBeansModel>>.value(
                  <_i11.CoffeeBeansModel>[],
                ),
          )
          as _i10.Future<List<_i11.CoffeeBeansModel>>);

  @override
  _i10.Future<List<String>> fetchOriginsForRoasters(
    List<String>? selectedRoasters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOriginsForRoasters, [selectedRoasters]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<double?> updateBeanWeightAfterBrew(
    String? beansUuid,
    double? usedAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightAfterBrew, [
              beansUuid,
              usedAmount,
            ]),
            returnValue: _i10.Future<double?>.value(),
            returnValueForMissingStub: _i10.Future<double?>.value(),
          )
          as _i10.Future<double?>);

  @override
  _i10.Future<double?> updateBeanWeightAfterBrewModification(
    String? beansUuid,
    double? coffeeAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightAfterBrewModification, [
              beansUuid,
              coffeeAmount,
            ]),
            returnValue: _i10.Future<double?>.value(),
            returnValueForMissingStub: _i10.Future<double?>.value(),
          )
          as _i10.Future<double?>);

  @override
  _i10.Future<double?> updateBeanWeightWhenBeansAdded(
    String? beansUuid,
    double? coffeeAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeanWeightWhenBeansAdded, [
              beansUuid,
              coffeeAmount,
            ]),
            returnValue: _i10.Future<double?>.value(),
            returnValueForMissingStub: _i10.Future<double?>.value(),
          )
          as _i10.Future<double?>);

  @override
  void printCacheStats() => super.noSuchMethod(
    Invocation.method(#printCacheStats, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StackRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRouter extends _i1.Mock implements _i5.StackRouter {
  @override
  _i4.Key get key =>
      (super.noSuchMethod(
            Invocation.getter(#key),
            returnValue: _FakeKey_2(this, Invocation.getter(#key)),
            returnValueForMissingStub: _FakeKey_2(
              this,
              Invocation.getter(#key),
            ),
          )
          as _i4.Key);

  @override
  _i4.Key get matchId =>
      (super.noSuchMethod(
            Invocation.getter(#matchId),
            returnValue: _FakeKey_2(this, Invocation.getter(#matchId)),
            returnValueForMissingStub: _FakeKey_2(
              this,
              Invocation.getter(#matchId),
            ),
          )
          as _i4.Key);

  @override
  _i5.PendingRoutesHandler get pendingRoutesHandler =>
      (super.noSuchMethod(
            Invocation.getter(#pendingRoutesHandler),
            returnValue: _FakePendingRoutesHandler_3(
              this,
              Invocation.getter(#pendingRoutesHandler),
            ),
            returnValueForMissingStub: _FakePendingRoutesHandler_3(
              this,
              Invocation.getter(#pendingRoutesHandler),
            ),
          )
          as _i5.PendingRoutesHandler);

  @override
  int get stateHash =>
      (super.noSuchMethod(
            Invocation.getter(#stateHash),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.PagelessRoutesObserver get pagelessRoutesObserver =>
      (super.noSuchMethod(
            Invocation.getter(#pagelessRoutesObserver),
            returnValue: _FakePagelessRoutesObserver_4(
              this,
              Invocation.getter(#pagelessRoutesObserver),
            ),
            returnValueForMissingStub: _FakePagelessRoutesObserver_4(
              this,
              Invocation.getter(#pagelessRoutesObserver),
            ),
          )
          as _i5.PagelessRoutesObserver);

  @override
  _i5.ActiveGuardObserver get activeGuardObserver =>
      (super.noSuchMethod(
            Invocation.getter(#activeGuardObserver),
            returnValue: _FakeActiveGuardObserver_5(
              this,
              Invocation.getter(#activeGuardObserver),
            ),
            returnValueForMissingStub: _FakeActiveGuardObserver_5(
              this,
              Invocation.getter(#activeGuardObserver),
            ),
          )
          as _i5.ActiveGuardObserver);

  @override
  _i4.GlobalKey<_i4.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_6<_i4.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_6<_i4.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i4.GlobalKey<_i4.NavigatorState>);

  @override
  _i5.RouteCollection get routeCollection =>
      (super.noSuchMethod(
            Invocation.getter(#routeCollection),
            returnValue: _FakeRouteCollection_7(
              this,
              Invocation.getter(#routeCollection),
            ),
            returnValueForMissingStub: _FakeRouteCollection_7(
              this,
              Invocation.getter(#routeCollection),
            ),
          )
          as _i5.RouteCollection);

  @override
  _i6.RouteMatcher get matcher =>
      (super.noSuchMethod(
            Invocation.getter(#matcher),
            returnValue: _FakeRouteMatcher_8(this, Invocation.getter(#matcher)),
            returnValueForMissingStub: _FakeRouteMatcher_8(
              this,
              Invocation.getter(#matcher),
            ),
          )
          as _i6.RouteMatcher);

  @override
  _i5.RouteData<dynamic> get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeRouteData_9<dynamic>(
              this,
              Invocation.getter(#current),
            ),
            returnValueForMissingStub: _FakeRouteData_9<dynamic>(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i5.RouteData<dynamic>);

  @override
  _i5.RouteData<dynamic> get topRoute =>
      (super.noSuchMethod(
            Invocation.getter(#topRoute),
            returnValue: _FakeRouteData_9<dynamic>(
              this,
              Invocation.getter(#topRoute),
            ),
            returnValueForMissingStub: _FakeRouteData_9<dynamic>(
              this,
              Invocation.getter(#topRoute),
            ),
          )
          as _i5.RouteData<dynamic>);

  @override
  bool get hasPagelessTopRoute =>
      (super.noSuchMethod(
            Invocation.getter(#hasPagelessTopRoute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i5.AutoRoutePage<dynamic>> get stack =>
      (super.noSuchMethod(
            Invocation.getter(#stack),
            returnValue: <_i5.AutoRoutePage<dynamic>>[],
            returnValueForMissingStub: <_i5.AutoRoutePage<dynamic>>[],
          )
          as List<_i5.AutoRoutePage<dynamic>>);

  @override
  bool get ignorePopCompleters =>
      (super.noSuchMethod(
            Invocation.getter(#ignorePopCompleters),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.GlobalObjectKey<_i4.State<_i4.StatefulWidget>> get globalRouterKey =>
      (super.noSuchMethod(
            Invocation.getter(#globalRouterKey),
            returnValue: _FakeGlobalObjectKey_10<_i4.State<_i4.StatefulWidget>>(
              this,
              Invocation.getter(#globalRouterKey),
            ),
            returnValueForMissingStub:
                _FakeGlobalObjectKey_10<_i4.State<_i4.StatefulWidget>>(
                  this,
                  Invocation.getter(#globalRouterKey),
                ),
          )
          as _i4.GlobalObjectKey<_i4.State<_i4.StatefulWidget>>);

  @override
  List<_i5.RoutingController> get childControllers =>
      (super.noSuchMethod(
            Invocation.getter(#childControllers),
            returnValue: <_i5.RoutingController>[],
            returnValueForMissingStub: <_i5.RoutingController>[],
          )
          as List<_i5.RoutingController>);

  @override
  _i7.NavigationHistory get navigationHistory =>
      (super.noSuchMethod(
            Invocation.getter(#navigationHistory),
            returnValue: _FakeNavigationHistory_11(
              this,
              Invocation.getter(#navigationHistory),
            ),
            returnValueForMissingStub: _FakeNavigationHistory_11(
              this,
              Invocation.getter(#navigationHistory),
            ),
          )
          as _i7.NavigationHistory);

  @override
  _i5.UrlState get urlState =>
      (super.noSuchMethod(
            Invocation.getter(#urlState),
            returnValue: _FakeUrlState_12(this, Invocation.getter(#urlState)),
            returnValueForMissingStub: _FakeUrlState_12(
              this,
              Invocation.getter(#urlState),
            ),
          )
          as _i5.UrlState);

  @override
  String get currentPath =>
      (super.noSuchMethod(
            Invocation.getter(#currentPath),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#currentPath),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#currentPath),
            ),
          )
          as String);

  @override
  String get currentUrl =>
      (super.noSuchMethod(
            Invocation.getter(#currentUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#currentUrl),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#currentUrl),
            ),
          )
          as String);

  @override
  List<_i5.RouteData<dynamic>> get stackData =>
      (super.noSuchMethod(
            Invocation.getter(#stackData),
            returnValue: <_i5.RouteData<dynamic>>[],
            returnValueForMissingStub: <_i5.RouteData<dynamic>>[],
          )
          as List<_i5.RouteData<dynamic>>);

  @override
  bool get managedByWidget =>
      (super.noSuchMethod(
            Invocation.getter(#managedByWidget),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isTopMost =>
      (super.noSuchMethod(
            Invocation.getter(#isTopMost),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canNavigateBack =>
      (super.noSuchMethod(
            Invocation.getter(#canNavigateBack),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.RootStackRouter get root =>
      (super.noSuchMethod(
            Invocation.getter(#root),
            returnValue: _FakeRootStackRouter_13(
              this,
              Invocation.getter(#root),
            ),
            returnValueForMissingStub: _FakeRootStackRouter_13(
              this,
              Invocation.getter(#root),
            ),
          )
          as _i5.RootStackRouter);

  @override
  bool get isRoot =>
      (super.noSuchMethod(
            Invocation.getter(#isRoot),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.RouteMatch<dynamic> get topMatch =>
      (super.noSuchMethod(
            Invocation.getter(#topMatch),
            returnValue: _FakeRouteMatch_14<dynamic>(
              this,
              Invocation.getter(#topMatch),
            ),
            returnValueForMissingStub: _FakeRouteMatch_14<dynamic>(
              this,
              Invocation.getter(#topMatch),
            ),
          )
          as _i5.RouteMatch<dynamic>);

  @override
  _i5.RouteData<dynamic> get routeData =>
      (super.noSuchMethod(
            Invocation.getter(#routeData),
            returnValue: _FakeRouteData_9<dynamic>(
              this,
              Invocation.getter(#routeData),
            ),
            returnValueForMissingStub: _FakeRouteData_9<dynamic>(
              this,
              Invocation.getter(#routeData),
            ),
          )
          as _i5.RouteData<dynamic>);

  @override
  bool get hasEntries =>
      (super.noSuchMethod(
            Invocation.getter(#hasEntries),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get pageCount =>
      (super.noSuchMethod(
            Invocation.getter(#pageCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i5.RouteMatch<dynamic>> get currentSegments =>
      (super.noSuchMethod(
            Invocation.getter(#currentSegments),
            returnValue: <_i5.RouteMatch<dynamic>>[],
            returnValueForMissingStub: <_i5.RouteMatch<dynamic>>[],
          )
          as List<_i5.RouteMatch<dynamic>>);

  @override
  set ignorePopCompleters(bool? value) => super.noSuchMethod(
    Invocation.setter(#ignorePopCompleters, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> reevaluateGuards() =>
      (super.noSuchMethod(
            Invocation.method(#reevaluateGuards, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  bool canPop({
    bool? ignoreChildRoutes = false,
    bool? ignoreParentRoutes = false,
    bool? ignorePagelessRoutes = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#canPop, [], {
              #ignoreChildRoutes: ignoreChildRoutes,
              #ignoreParentRoutes: ignoreParentRoutes,
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<T?> pushWidget<T extends Object?>(
    _i4.Widget? widget, {
    _i4.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
    bool? opaque = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushWidget,
              [widget],
              {
                #transitionBuilder: transitionBuilder,
                #fullscreenDialog: fullscreenDialog,
                #transitionDuration: transitionDuration,
                #opaque: opaque,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> pushNativeRoute<T extends Object?>(_i4.Route<T>? route) =>
      (super.noSuchMethod(
            Invocation.method(#pushNativeRoute, [route]),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<bool> maybePop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#maybePop, [result]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#popForced, [result]),
    returnValueForMissingStub: null,
  );

  @override
  bool removeLast() =>
      (super.noSuchMethod(
            Invocation.method(#removeLast, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void removeRoute(_i5.RouteData<dynamic>? route, {bool? notify = true}) =>
      super.noSuchMethod(
        Invocation.method(#removeRoute, [route], {#notify: notify}),
        returnValueForMissingStub: null,
      );

  @override
  void onPopPage(_i5.AutoRoutePage<Object?>? page) => super.noSuchMethod(
    Invocation.method(#onPopPage, [page]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<T?> push<T extends Object?>(
    _i5.PageRouteInfo<Object?>? route, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#push, [route], {#onFailure: onFailure}),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<void> insert(
    _i5.PageRouteInfo<Object?>? route, {
    int? index = 0,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [route],
              {#index: index, #onFailure: onFailure},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<T?> replace<T extends Object?>(
    _i5.PageRouteInfo<Object?>? route, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [route], {#onFailure: onFailure}),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<void> pushAll(
    List<_i5.PageRouteInfo<Object?>>? routes, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushAll, [routes], {#onFailure: onFailure}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> popAndPushAll(
    List<_i5.PageRouteInfo<Object?>>? routes, {
    dynamic onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #popAndPushAll,
              [routes],
              {#onFailure: onFailure},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> replaceAll(
    List<_i5.PageRouteInfo<Object?>>? routes, {
    _i5.OnNavigationFailure? onFailure,
    bool? updateExistingRoutes = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceAll,
              [routes],
              {
                #onFailure: onFailure,
                #updateExistingRoutes: updateExistingRoutes,
              },
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void popUntilRoot() => super.noSuchMethod(
    Invocation.method(#popUntilRoot, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<T?> popAndPush<T extends Object?, TO extends Object?>(
    _i5.PageRouteInfo<Object?>? route, {
    TO? result,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #popAndPush,
              [route],
              {#result: result, #onFailure: onFailure},
            ),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  bool removeUntil(_i5.RouteDataPredicate? predicate, {bool? scoped = true}) =>
      (super.noSuchMethod(
            Invocation.method(#removeUntil, [predicate], {#scoped: scoped}),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void popUntil(_i4.RoutePredicate? predicate, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntil, [predicate], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  bool removeWhere(_i5.RouteDataPredicate? predicate, {bool? notify = true}) =>
      (super.noSuchMethod(
            Invocation.method(#removeWhere, [predicate], {#notify: notify}),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void updateDeclarativeRoutes(List<_i5.PageRouteInfo<Object?>>? routes) =>
      super.noSuchMethod(
        Invocation.method(#updateDeclarativeRoutes, [routes]),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> navigateAll(
    List<_i5.RouteMatch<dynamic>>? routes, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigateAll, [routes], {#onFailure: onFailure}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<T?> pushAndPopUntil<T extends Object?>(
    _i5.PageRouteInfo<Object?>? route, {
    required _i4.RoutePredicate? predicate,
    bool? scopedPopUntil = true,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushAndPopUntil,
              [route],
              {
                #predicate: predicate,
                #scopedPopUntil: scopedPopUntil,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> replacePath<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replacePath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> replaceNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> pushPath<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushPath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  _i10.Future<T?> pushNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i10.Future<T?>.value(),
            returnValueForMissingStub: _i10.Future<T?>.value(),
          )
          as _i10.Future<T?>);

  @override
  void popUntilRouteWithName(String? name, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntilRouteWithName, [name], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  void popUntilRouteWithPath(String? path, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntilRouteWithPath, [path], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  void markUrlStateForReplace() => super.noSuchMethod(
    Invocation.method(#markUrlStateForReplace, []),
    returnValueForMissingStub: null,
  );

  @override
  void attachChildController(_i5.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(#attachChildController, [childController]),
        returnValueForMissingStub: null,
      );

  @override
  void removeChildController(_i5.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(#removeChildController, [childController]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAll({bool? forceUrlRebuild = false}) => super.noSuchMethod(
    Invocation.method(#notifyAll, [], {#forceUrlRebuild: forceUrlRebuild}),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.HierarchySegment> currentHierarchy({
    bool? asPath = false,
    bool? ignorePending = false,
    bool? ignoreParams = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#currentHierarchy, [], {
              #asPath: asPath,
              #ignorePending: ignorePending,
              #ignoreParams: ignoreParams,
            }),
            returnValue: <_i5.HierarchySegment>[],
            returnValueForMissingStub: <_i5.HierarchySegment>[],
          )
          as List<_i5.HierarchySegment>);

  @override
  bool isRouteActive(String? routeName) =>
      (super.noSuchMethod(
            Invocation.method(#isRouteActive, [routeName]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isRouteDataActive(_i5.RouteData<dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#isRouteDataActive, [data]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isPathActive(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#isPathActive, [path]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.RouteMatch<dynamic>? match(_i5.PageRouteInfo<Object?>? route) =>
      (super.noSuchMethod(
            Invocation.method(#match, [route]),
            returnValueForMissingStub: null,
          )
          as _i5.RouteMatch<dynamic>?);

  @override
  _i10.Future<dynamic> navigate(
    _i5.PageRouteInfo<Object?>? route, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigate, [route], {#onFailure: onFailure}),
            returnValue: _i10.Future<dynamic>.value(),
            returnValueForMissingStub: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<void> navigatePath(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigatePath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> navigateNamed(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void back() => super.noSuchMethod(
    Invocation.method(#back, []),
    returnValueForMissingStub: null,
  );

  @override
  void pushPathState(Object? state) => super.noSuchMethod(
    Invocation.method(#pushPathState, [state]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#topMostRouter, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: _FakeRoutingController_15(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
            returnValueForMissingStub: _FakeRoutingController_15(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
          )
          as _i5.RoutingController);

  @override
  void updateRouteData(_i5.RouteData<dynamic>? data) => super.noSuchMethod(
    Invocation.method(#updateRouteData, [data]),
    returnValueForMissingStub: null,
  );

  @override
  T? innerRouterOf<T extends _i5.RoutingController>(String? routeName) =>
      (super.noSuchMethod(
            Invocation.method(#innerRouterOf, [routeName]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  _i10.Future<bool> maybePopTop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#maybePopTop, [result]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  void popTop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#popTop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  bool childrenCanPop({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#childrenCanPop, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool activeRouterCanPop({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#activeRouterCanPop, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.PageRouteInfo<Object?>? buildPageRoute(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildPageRoute,
              [path],
              {#includePrefixMatches: includePrefixMatches},
            ),
            returnValueForMissingStub: null,
          )
          as _i5.PageRouteInfo<Object?>?);

  @override
  List<_i5.PageRouteInfo<Object?>>? buildPageRoutesStack(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildPageRoutesStack,
              [path],
              {#includePrefixMatches: includePrefixMatches},
            ),
            returnValueForMissingStub: null,
          )
          as List<_i5.PageRouteInfo<Object?>>?);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
