import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:coffee_timer/database/extensions.dart';

/// Guards the offline-fallback seed assets against generator drift: every bundled
/// seed file must parse cleanly through the same `*CompanionExtension.fromJson`
/// methods the runtime sync uses. Files are generated by `tool/generate_seed.dart`.
void main() {
  const seedDir = 'assets/data/seed';

  List<Map<String, dynamic>> load(String fileName) {
    final file = File('$seedDir/$fileName');
    expect(file.existsSync(), isTrue, reason: '$fileName must exist (run tool/generate_seed.dart)');
    final rows = jsonDecode(file.readAsStringSync()) as List;
    expect(rows, isNotEmpty, reason: '$fileName must not be empty');
    return rows.cast<Map<String, dynamic>>();
  }

  test('recipes.json parses into recipes, localizations and steps', () {
    final rows = load('recipes.json');
    for (final j in rows) {
      RecipesCompanionExtension.fromJson(j);
      for (final l in (j['recipe_localization'] as List).cast<Map<String, dynamic>>()) {
        RecipeLocalizationsCompanionExtension.fromJson(l);
      }
      for (final s in (j['steps'] as List).cast<Map<String, dynamic>>()) {
        StepsCompanionExtension.fromJson(s);
      }
    }
  });

  test('brewing_methods.json parses', () {
    for (final j in load('brewing_methods.json')) {
      BrewingMethodsCompanionExtension.fromJson(j);
    }
  });

  test('supported_locales.json parses', () {
    for (final j in load('supported_locales.json')) {
      SupportedLocalesCompanionExtension.fromJson(j);
    }
  });

  test('coffee_facts.json parses', () {
    for (final j in load('coffee_facts.json')) {
      CoffeeFactsCompanionExtension.fromJson(j);
    }
  });
}
